var wms_layers = [];


        var lyr_OpenStreetMap_0 = new ol.layer.Tile({
            'title': 'OpenStreetMap',
            'opacity': 1.000000,
            
            
            source: new ol.source.XYZ({
            attributions: ' ',
                url: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png'
            })
        });
var format_BADUNGcopy_1 = new ol.format.GeoJSON();
var features_BADUNGcopy_1 = format_BADUNGcopy_1.readFeatures(json_BADUNGcopy_1, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_BADUNGcopy_1 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_BADUNGcopy_1.addFeatures(features_BADUNGcopy_1);
var lyr_BADUNGcopy_1 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_BADUNGcopy_1, 
                style: style_BADUNGcopy_1,
                popuplayertitle: 'BADUNG copy',
                interactive: true,
    title: 'BADUNG copy<br />\
    <img src="styles/legend/BADUNGcopy_1_0.png" /> 0 - 7.3<br />\
    <img src="styles/legend/BADUNGcopy_1_1.png" /> 7.3 - 15.6<br />\
    <img src="styles/legend/BADUNGcopy_1_2.png" /> 15.6 - 31.2<br />' });
var format_BADUNG_2 = new ol.format.GeoJSON();
var features_BADUNG_2 = format_BADUNG_2.readFeatures(json_BADUNG_2, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_BADUNG_2 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_BADUNG_2.addFeatures(features_BADUNG_2);
var lyr_BADUNG_2 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_BADUNG_2, 
                style: style_BADUNG_2,
                popuplayertitle: 'BADUNG',
                interactive: true,
    title: 'BADUNG<br />\
    <img src="styles/legend/BADUNG_2_0.png" /> 0 - 7.3<br />\
    <img src="styles/legend/BADUNG_2_1.png" /> 7.3 - 15.6<br />\
    <img src="styles/legend/BADUNG_2_2.png" /> 15.6 - 31.2<br />' });
var format_Bangli_3 = new ol.format.GeoJSON();
var features_Bangli_3 = format_Bangli_3.readFeatures(json_Bangli_3, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Bangli_3 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Bangli_3.addFeatures(features_Bangli_3);
var lyr_Bangli_3 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Bangli_3, 
                style: style_Bangli_3,
                popuplayertitle: 'Bangli',
                interactive: true,
    title: 'Bangli<br />\
    <img src="styles/legend/Bangli_3_0.png" /> 0 - 7.2<br />\
    <img src="styles/legend/Bangli_3_1.png" /> 7.2 - 15.8<br />\
    <img src="styles/legend/Bangli_3_2.png" /> 15.8 - 32.4<br />' });
var format_Buleleng_4 = new ol.format.GeoJSON();
var features_Buleleng_4 = format_Buleleng_4.readFeatures(json_Buleleng_4, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Buleleng_4 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Buleleng_4.addFeatures(features_Buleleng_4);
var lyr_Buleleng_4 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Buleleng_4, 
                style: style_Buleleng_4,
                popuplayertitle: 'Buleleng',
                interactive: true,
    title: 'Buleleng<br />\
    <img src="styles/legend/Buleleng_4_0.png" /> 0 - 12<br />\
    <img src="styles/legend/Buleleng_4_1.png" /> 12 - 30<br />\
    <img src="styles/legend/Buleleng_4_2.png" /> 30 - 64<br />' });
var format_GIANYAR_5 = new ol.format.GeoJSON();
var features_GIANYAR_5 = format_GIANYAR_5.readFeatures(json_GIANYAR_5, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_GIANYAR_5 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_GIANYAR_5.addFeatures(features_GIANYAR_5);
var lyr_GIANYAR_5 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_GIANYAR_5, 
                style: style_GIANYAR_5,
                popuplayertitle: 'GIANYAR',
                interactive: true,
    title: 'GIANYAR<br />\
    <img src="styles/legend/GIANYAR_5_0.png" /> 2.1 - 10.3<br />\
    <img src="styles/legend/GIANYAR_5_1.png" /> 10.3 - 18.6<br />\
    <img src="styles/legend/GIANYAR_5_2.png" /> 18.6 - 29.7<br />' });
var format_Jembrana_6 = new ol.format.GeoJSON();
var features_Jembrana_6 = format_Jembrana_6.readFeatures(json_Jembrana_6, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Jembrana_6 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Jembrana_6.addFeatures(features_Jembrana_6);
var lyr_Jembrana_6 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Jembrana_6, 
                style: style_Jembrana_6,
                popuplayertitle: 'Jembrana',
                interactive: true,
    title: 'Jembrana<br />\
    <img src="styles/legend/Jembrana_6_0.png" /> 2.1 - 7.5<br />\
    <img src="styles/legend/Jembrana_6_1.png" /> 7.5 - 14.1<br />\
    <img src="styles/legend/Jembrana_6_2.png" /> 14.1 - 24.2<br />' });
var format_Karangasem_7 = new ol.format.GeoJSON();
var features_Karangasem_7 = format_Karangasem_7.readFeatures(json_Karangasem_7, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Karangasem_7 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Karangasem_7.addFeatures(features_Karangasem_7);
var lyr_Karangasem_7 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Karangasem_7, 
                style: style_Karangasem_7,
                popuplayertitle: 'Karangasem',
                interactive: true,
    title: 'Karangasem<br />\
    <img src="styles/legend/Karangasem_7_0.png" /> 1.6 - 8.4<br />\
    <img src="styles/legend/Karangasem_7_1.png" /> 8.4 - 17<br />\
    <img src="styles/legend/Karangasem_7_2.png" /> 17 - 25.4<br />' });
var format_Klungkung_8 = new ol.format.GeoJSON();
var features_Klungkung_8 = format_Klungkung_8.readFeatures(json_Klungkung_8, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Klungkung_8 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Klungkung_8.addFeatures(features_Klungkung_8);
var lyr_Klungkung_8 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Klungkung_8, 
                style: style_Klungkung_8,
                popuplayertitle: 'Klungkung',
                interactive: true,
    title: 'Klungkung<br />\
    <img src="styles/legend/Klungkung_8_0.png" /> 0 - 7.4<br />\
    <img src="styles/legend/Klungkung_8_1.png" /> 7.4 - 16.2<br />\
    <img src="styles/legend/Klungkung_8_2.png" /> 16.2 - 31.9<br />' });
var format_Tabanan_9 = new ol.format.GeoJSON();
var features_Tabanan_9 = format_Tabanan_9.readFeatures(json_Tabanan_9, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Tabanan_9 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Tabanan_9.addFeatures(features_Tabanan_9);
var lyr_Tabanan_9 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Tabanan_9, 
                style: style_Tabanan_9,
                popuplayertitle: 'Tabanan',
                interactive: true,
    title: 'Tabanan<br />\
    <img src="styles/legend/Tabanan_9_0.png" /> 0 - 8.3<br />\
    <img src="styles/legend/Tabanan_9_1.png" /> 8.3 - 17.7<br />\
    <img src="styles/legend/Tabanan_9_2.png" /> 17.7 - 30.2<br />' });
var format_Denpasar_10 = new ol.format.GeoJSON();
var features_Denpasar_10 = format_Denpasar_10.readFeatures(json_Denpasar_10, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Denpasar_10 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Denpasar_10.addFeatures(features_Denpasar_10);
var lyr_Denpasar_10 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Denpasar_10, 
                style: style_Denpasar_10,
                popuplayertitle: 'Denpasar',
                interactive: true,
    title: 'Denpasar<br />\
    <img src="styles/legend/Denpasar_10_0.png" /> 2.9 - 12<br />\
    <img src="styles/legend/Denpasar_10_1.png" /> 12 - 24.8<br />\
    <img src="styles/legend/Denpasar_10_2.png" /> 24.8 - 46.1<br />' });
var format_KecBadung_11 = new ol.format.GeoJSON();
var features_KecBadung_11 = format_KecBadung_11.readFeatures(json_KecBadung_11, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_KecBadung_11 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_KecBadung_11.addFeatures(features_KecBadung_11);
var lyr_KecBadung_11 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_KecBadung_11, 
                style: style_KecBadung_11,
                popuplayertitle: 'Kec. Badung',
                interactive: true,
    title: 'Kec. Badung<br />\
    <img src="styles/legend/KecBadung_11_0.png" /> 6 - 6<br />\
    <img src="styles/legend/KecBadung_11_1.png" /> 6 - 13.7<br />\
    <img src="styles/legend/KecBadung_11_2.png" /> 13.7 - 19.5<br />' });
var format_KecBangli_12 = new ol.format.GeoJSON();
var features_KecBangli_12 = format_KecBangli_12.readFeatures(json_KecBangli_12, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_KecBangli_12 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_KecBangli_12.addFeatures(features_KecBangli_12);
var lyr_KecBangli_12 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_KecBangli_12, 
                style: style_KecBangli_12,
                popuplayertitle: 'Kec. Bangli',
                interactive: true,
    title: 'Kec. Bangli<br />\
    <img src="styles/legend/KecBangli_12_0.png" /> 7.5 - 7.5<br />\
    <img src="styles/legend/KecBangli_12_1.png" /> 7.5 - 11.1<br />\
    <img src="styles/legend/KecBangli_12_2.png" /> 11.1 - 13.9<br />' });
var format_KecBuleleng_13 = new ol.format.GeoJSON();
var features_KecBuleleng_13 = format_KecBuleleng_13.readFeatures(json_KecBuleleng_13, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_KecBuleleng_13 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_KecBuleleng_13.addFeatures(features_KecBuleleng_13);
var lyr_KecBuleleng_13 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_KecBuleleng_13, 
                style: style_KecBuleleng_13,
                popuplayertitle: 'Kec. Buleleng',
                interactive: true,
    title: 'Kec. Buleleng<br />\
    <img src="styles/legend/KecBuleleng_13_0.png" /> 9.5 - 9.7<br />\
    <img src="styles/legend/KecBuleleng_13_1.png" /> 9.7 - 13.5<br />\
    <img src="styles/legend/KecBuleleng_13_2.png" /> 13.5 - 17.1<br />' });
var format_KecGianyar_14 = new ol.format.GeoJSON();
var features_KecGianyar_14 = format_KecGianyar_14.readFeatures(json_KecGianyar_14, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_KecGianyar_14 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_KecGianyar_14.addFeatures(features_KecGianyar_14);
var lyr_KecGianyar_14 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_KecGianyar_14, 
                style: style_KecGianyar_14,
                popuplayertitle: 'Kec. Gianyar',
                interactive: true,
    title: 'Kec. Gianyar<br />\
    <img src="styles/legend/KecGianyar_14_0.png" /> 7.4 - 7.4<br />\
    <img src="styles/legend/KecGianyar_14_1.png" /> 7.4 - 9.7<br />\
    <img src="styles/legend/KecGianyar_14_2.png" /> 9.7 - 13.5<br />' });
var format_KecJembrana_15 = new ol.format.GeoJSON();
var features_KecJembrana_15 = format_KecJembrana_15.readFeatures(json_KecJembrana_15, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_KecJembrana_15 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_KecJembrana_15.addFeatures(features_KecJembrana_15);
var lyr_KecJembrana_15 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_KecJembrana_15, 
                style: style_KecJembrana_15,
                popuplayertitle: 'Kec. Jembrana',
                interactive: true,
    title: 'Kec. Jembrana<br />\
    <img src="styles/legend/KecJembrana_15_0.png" /> 5.4 - 5.4<br />\
    <img src="styles/legend/KecJembrana_15_1.png" /> 5.4 - 7.9<br />\
    <img src="styles/legend/KecJembrana_15_2.png" /> 7.9 - 12.8<br />' });
var format_KecKarangasem_16 = new ol.format.GeoJSON();
var features_KecKarangasem_16 = format_KecKarangasem_16.readFeatures(json_KecKarangasem_16, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_KecKarangasem_16 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_KecKarangasem_16.addFeatures(features_KecKarangasem_16);
var lyr_KecKarangasem_16 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_KecKarangasem_16, 
                style: style_KecKarangasem_16,
                popuplayertitle: 'Kec. Karangasem',
                interactive: true,
    title: 'Kec. Karangasem<br />\
    <img src="styles/legend/KecKarangasem_16_0.png" /> 4.5 - 6.7<br />\
    <img src="styles/legend/KecKarangasem_16_1.png" /> 6.7 - 12.1<br />\
    <img src="styles/legend/KecKarangasem_16_2.png" /> 12.1 - 14<br />' });
var format_KecKlungkung_17 = new ol.format.GeoJSON();
var features_KecKlungkung_17 = format_KecKlungkung_17.readFeatures(json_KecKlungkung_17, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_KecKlungkung_17 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_KecKlungkung_17.addFeatures(features_KecKlungkung_17);
var lyr_KecKlungkung_17 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_KecKlungkung_17, 
                style: style_KecKlungkung_17,
                popuplayertitle: 'Kec. Klungkung',
                interactive: true,
    title: 'Kec. Klungkung<br />\
    <img src="styles/legend/KecKlungkung_17_0.png" /> 10.3 - 10.3<br />\
    <img src="styles/legend/KecKlungkung_17_1.png" /> 10.3 - 13.8<br />\
    <img src="styles/legend/KecKlungkung_17_2.png" /> 13.8 - 15.8<br />' });
var format_KecTabanan_18 = new ol.format.GeoJSON();
var features_KecTabanan_18 = format_KecTabanan_18.readFeatures(json_KecTabanan_18, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_KecTabanan_18 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_KecTabanan_18.addFeatures(features_KecTabanan_18);
var lyr_KecTabanan_18 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_KecTabanan_18, 
                style: style_KecTabanan_18,
                popuplayertitle: 'Kec. Tabanan',
                interactive: true,
    title: 'Kec. Tabanan<br />\
    <img src="styles/legend/KecTabanan_18_0.png" /> 6.1 - 8.3<br />\
    <img src="styles/legend/KecTabanan_18_1.png" /> 8.3 - 11.5<br />\
    <img src="styles/legend/KecTabanan_18_2.png" /> 11.5 - 16.6<br />' });
var format_KecDenpasar_19 = new ol.format.GeoJSON();
var features_KecDenpasar_19 = format_KecDenpasar_19.readFeatures(json_KecDenpasar_19, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_KecDenpasar_19 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_KecDenpasar_19.addFeatures(features_KecDenpasar_19);
var lyr_KecDenpasar_19 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_KecDenpasar_19, 
                style: style_KecDenpasar_19,
                popuplayertitle: 'Kec. Denpasar',
                interactive: true,
    title: 'Kec. Denpasar<br />\
    <img src="styles/legend/KecDenpasar_19_0.png" /> 13.4 - 13.4<br />\
    <img src="styles/legend/KecDenpasar_19_1.png" /> 13.4 - 20.1<br />\
    <img src="styles/legend/KecDenpasar_19_2.png" /> 20.1 - 21.4<br />' });
var format_BALI_20 = new ol.format.GeoJSON();
var features_BALI_20 = format_BALI_20.readFeatures(json_BALI_20, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_BALI_20 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_BALI_20.addFeatures(features_BALI_20);
var lyr_BALI_20 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_BALI_20, 
                style: style_BALI_20,
                popuplayertitle: 'BALI',
                interactive: true,
    title: 'BALI<br />\
    <img src="styles/legend/BALI_20_0.png" /> 9.7 - 9.9<br />\
    <img src="styles/legend/BALI_20_1.png" /> 9.9 - 14.3<br />\
    <img src="styles/legend/BALI_20_2.png" /> 14.3 - 19.1<br />' });
var group_KECAMATAN = new ol.layer.Group({
                                layers: [lyr_KecBadung_11,lyr_KecBangli_12,lyr_KecBuleleng_13,lyr_KecGianyar_14,lyr_KecJembrana_15,lyr_KecKarangasem_16,lyr_KecKlungkung_17,lyr_KecTabanan_18,lyr_KecDenpasar_19,],
                                fold: 'open',
                                title: 'KECAMATAN'});
var group_KELURAHAN = new ol.layer.Group({
                                layers: [lyr_BADUNG_2,lyr_Bangli_3,lyr_Buleleng_4,lyr_GIANYAR_5,lyr_Jembrana_6,lyr_Karangasem_7,lyr_Klungkung_8,lyr_Tabanan_9,lyr_Denpasar_10,],
                                fold: 'open',
                                title: 'KELURAHAN'});

lyr_OpenStreetMap_0.setVisible(true);lyr_BADUNGcopy_1.setVisible(true);lyr_BADUNG_2.setVisible(true);lyr_Bangli_3.setVisible(true);lyr_Buleleng_4.setVisible(true);lyr_GIANYAR_5.setVisible(true);lyr_Jembrana_6.setVisible(true);lyr_Karangasem_7.setVisible(true);lyr_Klungkung_8.setVisible(true);lyr_Tabanan_9.setVisible(true);lyr_Denpasar_10.setVisible(true);lyr_KecBadung_11.setVisible(true);lyr_KecBangli_12.setVisible(true);lyr_KecBuleleng_13.setVisible(true);lyr_KecGianyar_14.setVisible(true);lyr_KecJembrana_15.setVisible(true);lyr_KecKarangasem_16.setVisible(true);lyr_KecKlungkung_17.setVisible(true);lyr_KecTabanan_18.setVisible(true);lyr_KecDenpasar_19.setVisible(true);lyr_BALI_20.setVisible(true);
var layersList = [lyr_OpenStreetMap_0,lyr_BADUNGcopy_1,group_KELURAHAN,group_KECAMATAN,lyr_BALI_20];
lyr_BADUNGcopy_1.set('fieldAliases', {'KDPPUM': 'KDPPUM', 'NAMOBJ': 'NAMOBJ', 'REMARK': 'REMARK', 'KDPBPS': 'KDPBPS', 'FCODE': 'FCODE', 'LUASWH': 'LUASWH', 'UUPP': 'UUPP', 'SRS_ID': 'SRS_ID', 'LCODE': 'LCODE', 'METADATA': 'METADATA', 'KDEBPS': 'KDEBPS', 'KDEPUM': 'KDEPUM', 'KDCBPS': 'KDCBPS', 'KDCPUM': 'KDCPUM', 'KDBBPS': 'KDBBPS', 'KDBPUM': 'KDBPUM', 'WADMKD': 'WADMKD', 'WIADKD': 'WIADKD', 'WADMKC': 'WADMKC', 'WIADKC': 'WIADKC', 'WADMKK': 'WADMKK', 'WIADKK': 'WIADKK', 'WADMPR': 'WADMPR', 'WIADPR': 'WIADPR', 'TIPADM': 'TIPADM', 'SHAPE_Leng': 'SHAPE_Leng', 'SHAPE_Area': 'SHAPE_Area', 'jml_pus': 'jml_pus', });
lyr_BADUNG_2.set('fieldAliases', {'KDPPUM': 'KDPPUM', 'NAMOBJ': 'NAMOBJ', 'REMARK': 'REMARK', 'KDPBPS': 'KDPBPS', 'FCODE': 'FCODE', 'LUASWH': 'LUASWH', 'UUPP': 'UUPP', 'SRS_ID': 'SRS_ID', 'LCODE': 'LCODE', 'METADATA': 'METADATA', 'KDEBPS': 'KDEBPS', 'KDEPUM': 'KDEPUM', 'KDCBPS': 'KDCBPS', 'KDCPUM': 'KDCPUM', 'KDBBPS': 'KDBBPS', 'KDBPUM': 'KDBPUM', 'WADMKD': 'WADMKD', 'WIADKD': 'WIADKD', 'WADMKC': 'WADMKC', 'WIADKC': 'WIADKC', 'WADMKK': 'WADMKK', 'WIADKK': 'WIADKK', 'WADMPR': 'WADMPR', 'WIADPR': 'WIADPR', 'TIPADM': 'TIPADM', 'SHAPE_Leng': 'SHAPE_Leng', 'SHAPE_Area': 'SHAPE_Area', 'Badung_Kode_Kelurahan': 'Badung_Kode_Kelurahan', 'Badung_Kode_Kecamatan': 'Badung_Kode_Kecamatan', 'Badung_Jumlah_PUS': 'Badung_Jumlah_PUS', 'Badung_UnmetNeed_Spacing': 'Badung_UnmetNeed_Spacing', 'Badung_UnmetNeed_Limiting': 'Badung_UnmetNeed_Limiting', 'Badung_Jumlah_UnmetNeed': 'Badung_Jumlah_UnmetNeed', 'Badung_Persentase_UnmetNeed': 'Badung_Persentase_UnmetNeed', 'jml_pus': 'jml_pus', });
lyr_Bangli_3.set('fieldAliases', {'KDPPUM': 'KDPPUM', 'NAMOBJ': 'NAMOBJ', 'REMARK': 'REMARK', 'KDPBPS': 'KDPBPS', 'FCODE': 'FCODE', 'LUASWH': 'LUASWH', 'UUPP': 'UUPP', 'SRS_ID': 'SRS_ID', 'LCODE': 'LCODE', 'METADATA': 'METADATA', 'KDEBPS': 'KDEBPS', 'KDEPUM': 'KDEPUM', 'KDCBPS': 'KDCBPS', 'KDCPUM': 'KDCPUM', 'KDBBPS': 'KDBBPS', 'KDBPUM': 'KDBPUM', 'WADMKD': 'WADMKD', 'WIADKD': 'WIADKD', 'WADMKC': 'WADMKC', 'WIADKC': 'WIADKC', 'WADMKK': 'WADMKK', 'WIADKK': 'WIADKK', 'WADMPR': 'WADMPR', 'WIADPR': 'WIADPR', 'TIPADM': 'TIPADM', 'SHAPE_Leng': 'SHAPE_Leng', 'SHAPE_Area': 'SHAPE_Area', 'Bangli_Kode_Kelurahan': 'Bangli_Kode_Kelurahan', 'Bangli_Kode_Kecamatan': 'Bangli_Kode_Kecamatan', 'Bangli_Jumlah_PUS': 'Bangli_Jumlah_PUS', 'Bangli_UnmetNeed_Spacing': 'Bangli_UnmetNeed_Spacing', 'Bangli_UnmetNeed_Limiting': 'Bangli_UnmetNeed_Limiting', 'Bangli_Jumlah_UnmetNeed': 'Bangli_Jumlah_UnmetNeed', 'Bangli_Persentase_UnmetNeed': 'Bangli_Persentase_UnmetNeed', });
lyr_Buleleng_4.set('fieldAliases', {'KDPPUM': 'KDPPUM', 'NAMOBJ': 'NAMOBJ', 'REMARK': 'REMARK', 'KDPBPS': 'KDPBPS', 'FCODE': 'FCODE', 'LUASWH': 'LUASWH', 'UUPP': 'UUPP', 'SRS_ID': 'SRS_ID', 'LCODE': 'LCODE', 'METADATA': 'METADATA', 'KDEBPS': 'KDEBPS', 'KDEPUM': 'KDEPUM', 'KDCBPS': 'KDCBPS', 'KDCPUM': 'KDCPUM', 'KDBBPS': 'KDBBPS', 'KDBPUM': 'KDBPUM', 'WADMKD': 'WADMKD', 'WIADKD': 'WIADKD', 'WADMKC': 'WADMKC', 'WIADKC': 'WIADKC', 'WADMKK': 'WADMKK', 'WIADKK': 'WIADKK', 'WADMPR': 'WADMPR', 'WIADPR': 'WIADPR', 'TIPADM': 'TIPADM', 'SHAPE_Leng': 'SHAPE_Leng', 'SHAPE_Area': 'SHAPE_Area', 'Buleleng_Kode_Kelurahan': 'Buleleng_Kode_Kelurahan', 'Buleleng_Kode_Kecamatan': 'Buleleng_Kode_Kecamatan', 'Buleleng_Jumlah_PUS': 'Buleleng_Jumlah_PUS', 'Buleleng_UnmetNeed_Spacing': 'Buleleng_UnmetNeed_Spacing', 'Buleleng_UnmetNeed_Limiting': 'Buleleng_UnmetNeed_Limiting', 'Buleleng_Jumlah_UnmetNeed': 'Buleleng_Jumlah_UnmetNeed', 'Buleleng_Persentase_UnmetNeed': 'Buleleng_Persentase_UnmetNeed', });
lyr_GIANYAR_5.set('fieldAliases', {'KDPPUM': 'KDPPUM', 'NAMOBJ': 'NAMOBJ', 'REMARK': 'REMARK', 'KDPBPS': 'KDPBPS', 'FCODE': 'FCODE', 'LUASWH': 'LUASWH', 'UUPP': 'UUPP', 'SRS_ID': 'SRS_ID', 'LCODE': 'LCODE', 'METADATA': 'METADATA', 'KDEBPS': 'KDEBPS', 'KDEPUM': 'KDEPUM', 'KDCBPS': 'KDCBPS', 'KDCPUM': 'KDCPUM', 'KDBBPS': 'KDBBPS', 'KDBPUM': 'KDBPUM', 'WADMKD': 'WADMKD', 'WIADKD': 'WIADKD', 'WADMKC': 'WADMKC', 'WIADKC': 'WIADKC', 'WADMKK': 'WADMKK', 'WIADKK': 'WIADKK', 'WADMPR': 'WADMPR', 'WIADPR': 'WIADPR', 'TIPADM': 'TIPADM', 'SHAPE_Leng': 'SHAPE_Leng', 'SHAPE_Area': 'SHAPE_Area', 'Gianyar_Kode_Kelurahan': 'Gianyar_Kode_Kelurahan', 'Gianyar_Kode_Kecamatan': 'Gianyar_Kode_Kecamatan', 'Gianyar_Jumlah_PUS': 'Gianyar_Jumlah_PUS', 'Gianyar_UnmetNeed_Spacing': 'Gianyar_UnmetNeed_Spacing', 'Gianyar_UnmetNeed_Limiting': 'Gianyar_UnmetNeed_Limiting', 'Gianyar_Jumlah_UnmetNeed': 'Gianyar_Jumlah_UnmetNeed', 'Gianyar_Persentase_UnmetNeed': 'Gianyar_Persentase_UnmetNeed', });
lyr_Jembrana_6.set('fieldAliases', {'KDPPUM': 'KDPPUM', 'NAMOBJ': 'NAMOBJ', 'REMARK': 'REMARK', 'KDPBPS': 'KDPBPS', 'FCODE': 'FCODE', 'LUASWH': 'LUASWH', 'UUPP': 'UUPP', 'SRS_ID': 'SRS_ID', 'LCODE': 'LCODE', 'METADATA': 'METADATA', 'KDEBPS': 'KDEBPS', 'KDEPUM': 'KDEPUM', 'KDCBPS': 'KDCBPS', 'KDCPUM': 'KDCPUM', 'KDBBPS': 'KDBBPS', 'KDBPUM': 'KDBPUM', 'WADMKD': 'WADMKD', 'WIADKD': 'WIADKD', 'WADMKC': 'WADMKC', 'WIADKC': 'WIADKC', 'WADMKK': 'WADMKK', 'WIADKK': 'WIADKK', 'WADMPR': 'WADMPR', 'WIADPR': 'WIADPR', 'TIPADM': 'TIPADM', 'SHAPE_Leng': 'SHAPE_Leng', 'SHAPE_Area': 'SHAPE_Area', 'Jembrana_Kode_Kelurahan': 'Jembrana_Kode_Kelurahan', 'Jembrana_Kode_Kecamatan': 'Jembrana_Kode_Kecamatan', 'Jembrana_Jumlah_PUS': 'Jembrana_Jumlah_PUS', 'Jembrana_UnmetNeed_Spacing': 'Jembrana_UnmetNeed_Spacing', 'Jembrana_UnmetNeed_Limiting': 'Jembrana_UnmetNeed_Limiting', 'Jembrana_Jumlah_UnmetNeed': 'Jembrana_Jumlah_UnmetNeed', 'Jembrana_Persentase_UnmetNeed': 'Jembrana_Persentase_UnmetNeed', });
lyr_Karangasem_7.set('fieldAliases', {'KDPPUM': 'KDPPUM', 'NAMOBJ': 'NAMOBJ', 'REMARK': 'REMARK', 'KDPBPS': 'KDPBPS', 'FCODE': 'FCODE', 'LUASWH': 'LUASWH', 'UUPP': 'UUPP', 'SRS_ID': 'SRS_ID', 'LCODE': 'LCODE', 'METADATA': 'METADATA', 'KDEBPS': 'KDEBPS', 'KDEPUM': 'KDEPUM', 'KDCBPS': 'KDCBPS', 'KDCPUM': 'KDCPUM', 'KDBBPS': 'KDBBPS', 'KDBPUM': 'KDBPUM', 'WADMKD': 'WADMKD', 'WIADKD': 'WIADKD', 'WADMKC': 'WADMKC', 'WIADKC': 'WIADKC', 'WADMKK': 'WADMKK', 'WIADKK': 'WIADKK', 'WADMPR': 'WADMPR', 'WIADPR': 'WIADPR', 'TIPADM': 'TIPADM', 'SHAPE_Leng': 'SHAPE_Leng', 'SHAPE_Area': 'SHAPE_Area', 'Karangasem_Kode_Kelurahan': 'Karangasem_Kode_Kelurahan', 'Karangasem_Kode_Kecamatan': 'Karangasem_Kode_Kecamatan', 'Karangasem_Jumlah_PUS': 'Karangasem_Jumlah_PUS', 'Karangasem_UnmetNeed_Spacing': 'Karangasem_UnmetNeed_Spacing', 'Karangasem_UnmetNeed_Limiting': 'Karangasem_UnmetNeed_Limiting', 'Karangasem_Jumlah_UnmetNeed': 'Karangasem_Jumlah_UnmetNeed', 'Karangasem_Persentase_UnmetNeed': 'Karangasem_Persentase_UnmetNeed', });
lyr_Klungkung_8.set('fieldAliases', {'KDPPUM': 'KDPPUM', 'NAMOBJ': 'NAMOBJ', 'REMARK': 'REMARK', 'KDPBPS': 'KDPBPS', 'FCODE': 'FCODE', 'LUASWH': 'LUASWH', 'UUPP': 'UUPP', 'SRS_ID': 'SRS_ID', 'LCODE': 'LCODE', 'METADATA': 'METADATA', 'KDEBPS': 'KDEBPS', 'KDEPUM': 'KDEPUM', 'KDCBPS': 'KDCBPS', 'KDCPUM': 'KDCPUM', 'KDBBPS': 'KDBBPS', 'KDBPUM': 'KDBPUM', 'WADMKD': 'WADMKD', 'WIADKD': 'WIADKD', 'WADMKC': 'WADMKC', 'WIADKC': 'WIADKC', 'WADMKK': 'WADMKK', 'WIADKK': 'WIADKK', 'WADMPR': 'WADMPR', 'WIADPR': 'WIADPR', 'TIPADM': 'TIPADM', 'SHAPE_Leng': 'SHAPE_Leng', 'SHAPE_Area': 'SHAPE_Area', 'Klungkung_Kode_Kelurahan': 'Klungkung_Kode_Kelurahan', 'Klungkung_Kode_Kecamatan': 'Klungkung_Kode_Kecamatan', 'Klungkung_Jumlah_PUS': 'Klungkung_Jumlah_PUS', 'Klungkung_UnmetNeed_Spacing': 'Klungkung_UnmetNeed_Spacing', 'Klungkung_UnmetNeed_Limiting': 'Klungkung_UnmetNeed_Limiting', 'Klungkung_Jumlah_UnmetNeed': 'Klungkung_Jumlah_UnmetNeed', 'Klungkung_Persentase_UnmetNeed': 'Klungkung_Persentase_UnmetNeed', });
lyr_Tabanan_9.set('fieldAliases', {'KDPPUM': 'KDPPUM', 'NAMOBJ': 'NAMOBJ', 'REMARK': 'REMARK', 'KDPBPS': 'KDPBPS', 'FCODE': 'FCODE', 'LUASWH': 'LUASWH', 'UUPP': 'UUPP', 'SRS_ID': 'SRS_ID', 'LCODE': 'LCODE', 'METADATA': 'METADATA', 'KDEBPS': 'KDEBPS', 'KDEPUM': 'KDEPUM', 'KDCBPS': 'KDCBPS', 'KDCPUM': 'KDCPUM', 'KDBBPS': 'KDBBPS', 'KDBPUM': 'KDBPUM', 'WADMKD': 'WADMKD', 'WIADKD': 'WIADKD', 'WADMKC': 'WADMKC', 'WIADKC': 'WIADKC', 'WADMKK': 'WADMKK', 'WIADKK': 'WIADKK', 'WADMPR': 'WADMPR', 'WIADPR': 'WIADPR', 'TIPADM': 'TIPADM', 'SHAPE_Leng': 'SHAPE_Leng', 'SHAPE_Area': 'SHAPE_Area', 'Tabanan_Kode_Kelurahan': 'Tabanan_Kode_Kelurahan', 'Tabanan_Kode_Kecamatan': 'Tabanan_Kode_Kecamatan', 'Tabanan_Jumlah_PUS': 'Tabanan_Jumlah_PUS', 'Tabanan_UnmetNeed_Spacing': 'Tabanan_UnmetNeed_Spacing', 'Tabanan_UnmetNeed_Limiting': 'Tabanan_UnmetNeed_Limiting', 'Tabanan_Jumlah_UnmetNeed': 'Tabanan_Jumlah_UnmetNeed', 'Tabanan_Persentase_UnmetNeed': 'Tabanan_Persentase_UnmetNeed', });
lyr_Denpasar_10.set('fieldAliases', {'KDPPUM': 'KDPPUM', 'NAMOBJ': 'NAMOBJ', 'REMARK': 'REMARK', 'KDPBPS': 'KDPBPS', 'FCODE': 'FCODE', 'LUASWH': 'LUASWH', 'UUPP': 'UUPP', 'SRS_ID': 'SRS_ID', 'LCODE': 'LCODE', 'METADATA': 'METADATA', 'KDEBPS': 'KDEBPS', 'KDEPUM': 'KDEPUM', 'KDCBPS': 'KDCBPS', 'KDCPUM': 'KDCPUM', 'KDBBPS': 'KDBBPS', 'KDBPUM': 'KDBPUM', 'WADMKD': 'WADMKD', 'WIADKD': 'WIADKD', 'WADMKC': 'WADMKC', 'WIADKC': 'WIADKC', 'WADMKK': 'WADMKK', 'WIADKK': 'WIADKK', 'WADMPR': 'WADMPR', 'WIADPR': 'WIADPR', 'TIPADM': 'TIPADM', 'SHAPE_Leng': 'SHAPE_Leng', 'SHAPE_Area': 'SHAPE_Area', 'Denpasar_Kode_Kelurahan': 'Denpasar_Kode_Kelurahan', 'Denpasar_Kode_Kecamatan': 'Denpasar_Kode_Kecamatan', 'Denpasar_Jumlah_PUS': 'Denpasar_Jumlah_PUS', 'Denpasar_UnmetNeed_Spacing': 'Denpasar_UnmetNeed_Spacing', 'Denpasar_UnmetNeed_Limiting': 'Denpasar_UnmetNeed_Limiting', 'Denpasar_Jumlah_UnmetNeed': 'Denpasar_Jumlah_UnmetNeed', 'Denpasar_Persentase_UnmetNeed': 'Denpasar_Persentase_UnmetNeed', });
lyr_KecBadung_11.set('fieldAliases', {'KDPPUM': 'KDPPUM', 'NAMOBJ': 'NAMOBJ', 'REMARK': 'REMARK', 'KDPBPS': 'KDPBPS', 'FCODE': 'FCODE', 'LUASWH': 'LUASWH', 'UUPP': 'UUPP', 'SRS_ID': 'SRS_ID', 'LCODE': 'LCODE', 'METADATA': 'METADATA', 'KDEBPS': 'KDEBPS', 'KDEPUM': 'KDEPUM', 'KDCBPS': 'KDCBPS', 'KDCPUM': 'KDCPUM', 'KDBBPS': 'KDBBPS', 'KDBPUM': 'KDBPUM', 'WADMKD': 'WADMKD', 'WIADKD': 'WIADKD', 'WADMKC': 'WADMKC', 'WIADKC': 'WIADKC', 'WADMKK': 'WADMKK', 'WIADKK': 'WIADKK', 'WADMPR': 'WADMPR', 'WIADPR': 'WIADPR', 'TIPADM': 'TIPADM', 'SHAPE_Leng': 'SHAPE_Leng', 'SHAPE_Area': 'SHAPE_Area', 'KecBadung_Kode_Kecamatan': 'KecBadung_Kode_Kecamatan', 'KecBadung_Kode_Kabupaten': 'KecBadung_Kode_Kabupaten', 'KecBadung_Jumlah_PUS': 'KecBadung_Jumlah_PUS', 'KecBadung_UnmetNeed_Spacing': 'KecBadung_UnmetNeed_Spacing', 'KecBadung_UnmetNeed_Limiting': 'KecBadung_UnmetNeed_Limiting', 'KecBadung_Jumlah_UnmetNeed': 'KecBadung_Jumlah_UnmetNeed', 'KecBadung_Persentase_UnmetNeed': 'KecBadung_Persentase_UnmetNeed', });
lyr_KecBangli_12.set('fieldAliases', {'KDPPUM': 'KDPPUM', 'NAMOBJ': 'NAMOBJ', 'REMARK': 'REMARK', 'KDPBPS': 'KDPBPS', 'FCODE': 'FCODE', 'LUASWH': 'LUASWH', 'UUPP': 'UUPP', 'SRS_ID': 'SRS_ID', 'LCODE': 'LCODE', 'METADATA': 'METADATA', 'KDEBPS': 'KDEBPS', 'KDEPUM': 'KDEPUM', 'KDCBPS': 'KDCBPS', 'KDCPUM': 'KDCPUM', 'KDBBPS': 'KDBBPS', 'KDBPUM': 'KDBPUM', 'WADMKD': 'WADMKD', 'WIADKD': 'WIADKD', 'WADMKC': 'WADMKC', 'WIADKC': 'WIADKC', 'WADMKK': 'WADMKK', 'WIADKK': 'WIADKK', 'WADMPR': 'WADMPR', 'WIADPR': 'WIADPR', 'TIPADM': 'TIPADM', 'SHAPE_Leng': 'SHAPE_Leng', 'SHAPE_Area': 'SHAPE_Area', 'KecBangli_Kode_Kecamatan': 'KecBangli_Kode_Kecamatan', 'KecBangli_Kode_Kabupaten': 'KecBangli_Kode_Kabupaten', 'KecBangli_Jumlah_PUS': 'KecBangli_Jumlah_PUS', 'KecBangli_UnmetNeed_Spacing': 'KecBangli_UnmetNeed_Spacing', 'KecBangli_UnmetNeed_Limiting': 'KecBangli_UnmetNeed_Limiting', 'KecBangli_Jumlah_UnmetNeed': 'KecBangli_Jumlah_UnmetNeed', 'KecBangli_Persentase_UnmetNeed': 'KecBangli_Persentase_UnmetNeed', });
lyr_KecBuleleng_13.set('fieldAliases', {'KDPPUM': 'KDPPUM', 'NAMOBJ': 'NAMOBJ', 'REMARK': 'REMARK', 'KDPBPS': 'KDPBPS', 'FCODE': 'FCODE', 'LUASWH': 'LUASWH', 'UUPP': 'UUPP', 'SRS_ID': 'SRS_ID', 'LCODE': 'LCODE', 'METADATA': 'METADATA', 'KDEBPS': 'KDEBPS', 'KDEPUM': 'KDEPUM', 'KDCBPS': 'KDCBPS', 'KDCPUM': 'KDCPUM', 'KDBBPS': 'KDBBPS', 'KDBPUM': 'KDBPUM', 'WADMKD': 'WADMKD', 'WIADKD': 'WIADKD', 'WADMKC': 'WADMKC', 'WIADKC': 'WIADKC', 'WADMKK': 'WADMKK', 'WIADKK': 'WIADKK', 'WADMPR': 'WADMPR', 'WIADPR': 'WIADPR', 'TIPADM': 'TIPADM', 'SHAPE_Leng': 'SHAPE_Leng', 'SHAPE_Area': 'SHAPE_Area', 'KecBuleleng_Kode_Kecamatan': 'KecBuleleng_Kode_Kecamatan', 'KecBuleleng_Kode_Kabupaten': 'KecBuleleng_Kode_Kabupaten', 'KecBuleleng_Jumlah_PUS': 'KecBuleleng_Jumlah_PUS', 'KecBuleleng_UnmetNeed_Spacing': 'KecBuleleng_UnmetNeed_Spacing', 'KecBuleleng_UnmetNeed_Limiting': 'KecBuleleng_UnmetNeed_Limiting', 'KecBuleleng_Jumlah_UnmetNeed': 'KecBuleleng_Jumlah_UnmetNeed', 'KecBuleleng_Persentase_UnmetNeed': 'KecBuleleng_Persentase_UnmetNeed', });
lyr_KecGianyar_14.set('fieldAliases', {'KDPPUM': 'KDPPUM', 'NAMOBJ': 'NAMOBJ', 'REMARK': 'REMARK', 'KDPBPS': 'KDPBPS', 'FCODE': 'FCODE', 'LUASWH': 'LUASWH', 'UUPP': 'UUPP', 'SRS_ID': 'SRS_ID', 'LCODE': 'LCODE', 'METADATA': 'METADATA', 'KDEBPS': 'KDEBPS', 'KDEPUM': 'KDEPUM', 'KDCBPS': 'KDCBPS', 'KDCPUM': 'KDCPUM', 'KDBBPS': 'KDBBPS', 'KDBPUM': 'KDBPUM', 'WADMKD': 'WADMKD', 'WIADKD': 'WIADKD', 'WADMKC': 'WADMKC', 'WIADKC': 'WIADKC', 'WADMKK': 'WADMKK', 'WIADKK': 'WIADKK', 'WADMPR': 'WADMPR', 'WIADPR': 'WIADPR', 'TIPADM': 'TIPADM', 'SHAPE_Leng': 'SHAPE_Leng', 'SHAPE_Area': 'SHAPE_Area', 'KecGianyar_Kode_Kecamatan': 'KecGianyar_Kode_Kecamatan', 'KecGianyar_Kode_Kabupaten': 'KecGianyar_Kode_Kabupaten', 'KecGianyar_Jumlah_PUS': 'KecGianyar_Jumlah_PUS', 'KecGianyar_UnmetNeed_Spacing': 'KecGianyar_UnmetNeed_Spacing', 'KecGianyar_UnmetNeed_Limiting': 'KecGianyar_UnmetNeed_Limiting', 'KecGianyar_Jumlah_UnmetNeed': 'KecGianyar_Jumlah_UnmetNeed', 'KecGianyar_Persentase_UnmetNeed': 'KecGianyar_Persentase_UnmetNeed', });
lyr_KecJembrana_15.set('fieldAliases', {'KDPPUM': 'KDPPUM', 'NAMOBJ': 'NAMOBJ', 'REMARK': 'REMARK', 'KDPBPS': 'KDPBPS', 'FCODE': 'FCODE', 'LUASWH': 'LUASWH', 'UUPP': 'UUPP', 'SRS_ID': 'SRS_ID', 'LCODE': 'LCODE', 'METADATA': 'METADATA', 'KDEBPS': 'KDEBPS', 'KDEPUM': 'KDEPUM', 'KDCBPS': 'KDCBPS', 'KDCPUM': 'KDCPUM', 'KDBBPS': 'KDBBPS', 'KDBPUM': 'KDBPUM', 'WADMKD': 'WADMKD', 'WIADKD': 'WIADKD', 'WADMKC': 'WADMKC', 'WIADKC': 'WIADKC', 'WADMKK': 'WADMKK', 'WIADKK': 'WIADKK', 'WADMPR': 'WADMPR', 'WIADPR': 'WIADPR', 'TIPADM': 'TIPADM', 'SHAPE_Leng': 'SHAPE_Leng', 'SHAPE_Area': 'SHAPE_Area', 'KecJembrana_Kode_Kecamatan': 'KecJembrana_Kode_Kecamatan', 'KecJembrana_Kode_Kabupaten': 'KecJembrana_Kode_Kabupaten', 'KecJembrana_Jumlah_PUS': 'KecJembrana_Jumlah_PUS', 'KecJembrana_UnmetNeed_Spacing': 'KecJembrana_UnmetNeed_Spacing', 'KecJembrana_UnmetNeed_Limiting': 'KecJembrana_UnmetNeed_Limiting', 'KecJembrana_Jumlah_UnmetNeed': 'KecJembrana_Jumlah_UnmetNeed', 'KecJembrana_Persentase_UnmetNeed': 'KecJembrana_Persentase_UnmetNeed', });
lyr_KecKarangasem_16.set('fieldAliases', {'KDPPUM': 'KDPPUM', 'NAMOBJ': 'NAMOBJ', 'REMARK': 'REMARK', 'KDPBPS': 'KDPBPS', 'FCODE': 'FCODE', 'LUASWH': 'LUASWH', 'UUPP': 'UUPP', 'SRS_ID': 'SRS_ID', 'LCODE': 'LCODE', 'METADATA': 'METADATA', 'KDEBPS': 'KDEBPS', 'KDEPUM': 'KDEPUM', 'KDCBPS': 'KDCBPS', 'KDCPUM': 'KDCPUM', 'KDBBPS': 'KDBBPS', 'KDBPUM': 'KDBPUM', 'WADMKD': 'WADMKD', 'WIADKD': 'WIADKD', 'WADMKC': 'WADMKC', 'WIADKC': 'WIADKC', 'WADMKK': 'WADMKK', 'WIADKK': 'WIADKK', 'WADMPR': 'WADMPR', 'WIADPR': 'WIADPR', 'TIPADM': 'TIPADM', 'SHAPE_Leng': 'SHAPE_Leng', 'SHAPE_Area': 'SHAPE_Area', 'KecKarangasem_Kode_Kecamatan': 'KecKarangasem_Kode_Kecamatan', 'KecKarangasem_Kode_Kabupaten': 'KecKarangasem_Kode_Kabupaten', 'KecKarangasem_Jumlah_PUS': 'KecKarangasem_Jumlah_PUS', 'KecKarangasem_UnmetNeed_Spacing': 'KecKarangasem_UnmetNeed_Spacing', 'KecKarangasem_UnmetNeed_Limiting': 'KecKarangasem_UnmetNeed_Limiting', 'KecKarangasem_Jumlah_UnmetNeed': 'KecKarangasem_Jumlah_UnmetNeed', 'KecKarangasem_Persentase_UnmetNeed': 'KecKarangasem_Persentase_UnmetNeed', });
lyr_KecKlungkung_17.set('fieldAliases', {'KDPPUM': 'KDPPUM', 'NAMOBJ': 'NAMOBJ', 'REMARK': 'REMARK', 'KDPBPS': 'KDPBPS', 'FCODE': 'FCODE', 'LUASWH': 'LUASWH', 'UUPP': 'UUPP', 'SRS_ID': 'SRS_ID', 'LCODE': 'LCODE', 'METADATA': 'METADATA', 'KDEBPS': 'KDEBPS', 'KDEPUM': 'KDEPUM', 'KDCBPS': 'KDCBPS', 'KDCPUM': 'KDCPUM', 'KDBBPS': 'KDBBPS', 'KDBPUM': 'KDBPUM', 'WADMKD': 'WADMKD', 'WIADKD': 'WIADKD', 'WADMKC': 'WADMKC', 'WIADKC': 'WIADKC', 'WADMKK': 'WADMKK', 'WIADKK': 'WIADKK', 'WADMPR': 'WADMPR', 'WIADPR': 'WIADPR', 'TIPADM': 'TIPADM', 'SHAPE_Leng': 'SHAPE_Leng', 'SHAPE_Area': 'SHAPE_Area', 'KecKlungkung_Kode_Kecamatan': 'KecKlungkung_Kode_Kecamatan', 'KecKlungkung_Kode_Kabupaten': 'KecKlungkung_Kode_Kabupaten', 'KecKlungkung_Jumlah_PUS': 'KecKlungkung_Jumlah_PUS', 'KecKlungkung_UnmetNeed_Spacing': 'KecKlungkung_UnmetNeed_Spacing', 'KecKlungkung_UnmetNeed_Limiting': 'KecKlungkung_UnmetNeed_Limiting', 'KecKlungkung_Jumlah_UnmetNeed': 'KecKlungkung_Jumlah_UnmetNeed', 'KecKlungkung_Persentase_UnmetNeed': 'KecKlungkung_Persentase_UnmetNeed', });
lyr_KecTabanan_18.set('fieldAliases', {'KDPPUM': 'KDPPUM', 'NAMOBJ': 'NAMOBJ', 'REMARK': 'REMARK', 'KDPBPS': 'KDPBPS', 'FCODE': 'FCODE', 'LUASWH': 'LUASWH', 'UUPP': 'UUPP', 'SRS_ID': 'SRS_ID', 'LCODE': 'LCODE', 'METADATA': 'METADATA', 'KDEBPS': 'KDEBPS', 'KDEPUM': 'KDEPUM', 'KDCBPS': 'KDCBPS', 'KDCPUM': 'KDCPUM', 'KDBBPS': 'KDBBPS', 'KDBPUM': 'KDBPUM', 'WADMKD': 'WADMKD', 'WIADKD': 'WIADKD', 'WADMKC': 'WADMKC', 'WIADKC': 'WIADKC', 'WADMKK': 'WADMKK', 'WIADKK': 'WIADKK', 'WADMPR': 'WADMPR', 'WIADPR': 'WIADPR', 'TIPADM': 'TIPADM', 'SHAPE_Leng': 'SHAPE_Leng', 'SHAPE_Area': 'SHAPE_Area', 'KecTabanan_Kode_Kecamatan': 'KecTabanan_Kode_Kecamatan', 'KecTabanan_Kode_Kabupaten': 'KecTabanan_Kode_Kabupaten', 'KecTabanan_Jumlah_PUS': 'KecTabanan_Jumlah_PUS', 'KecTabanan_UnmetNeed_Spacing': 'KecTabanan_UnmetNeed_Spacing', 'KecTabanan_UnmetNeed_Limiting': 'KecTabanan_UnmetNeed_Limiting', 'KecTabanan_Jumlah_UnmetNeed': 'KecTabanan_Jumlah_UnmetNeed', 'KecTabanan_Persentase_UnmetNeed': 'KecTabanan_Persentase_UnmetNeed', });
lyr_KecDenpasar_19.set('fieldAliases', {'KDPPUM': 'KDPPUM', 'NAMOBJ': 'NAMOBJ', 'REMARK': 'REMARK', 'KDPBPS': 'KDPBPS', 'FCODE': 'FCODE', 'LUASWH': 'LUASWH', 'UUPP': 'UUPP', 'SRS_ID': 'SRS_ID', 'LCODE': 'LCODE', 'METADATA': 'METADATA', 'KDEBPS': 'KDEBPS', 'KDEPUM': 'KDEPUM', 'KDCBPS': 'KDCBPS', 'KDCPUM': 'KDCPUM', 'KDBBPS': 'KDBBPS', 'KDBPUM': 'KDBPUM', 'WADMKD': 'WADMKD', 'WIADKD': 'WIADKD', 'WADMKC': 'WADMKC', 'WIADKC': 'WIADKC', 'WADMKK': 'WADMKK', 'WIADKK': 'WIADKK', 'WADMPR': 'WADMPR', 'WIADPR': 'WIADPR', 'TIPADM': 'TIPADM', 'SHAPE_Leng': 'SHAPE_Leng', 'SHAPE_Area': 'SHAPE_Area', 'KecDenpasar_Kode_Kecamatan': 'KecDenpasar_Kode_Kecamatan', 'KecDenpasar_Kode_Kabupaten': 'KecDenpasar_Kode_Kabupaten', 'KecDenpasar_Jumlah_PUS': 'KecDenpasar_Jumlah_PUS', 'KecDenpasar_UnmetNeed_Spacing': 'KecDenpasar_UnmetNeed_Spacing', 'KecDenpasar_UnmetNeed_Limiting': 'KecDenpasar_UnmetNeed_Limiting', 'KecDenpasar_Jumlah_UnmetNeed': 'KecDenpasar_Jumlah_UnmetNeed', 'KecDenpasar_Persentase_UnmetNeed': 'KecDenpasar_Persentase_UnmetNeed', });
lyr_BALI_20.set('fieldAliases', {'PROVINSI': 'PROVINSI', 'KABKOT': 'KABKOT', 'KECAMATAN': 'KECAMATAN', 'KODE': 'KODE', 'DESA': 'DESA', 'Kabupaten_Kode_Kabupaten': 'Kabupaten_Kode_Kabupaten', 'Kabupaten_Jumlah_PUS': 'Kabupaten_Jumlah_PUS', 'Kabupaten_UnmetNeed_Spacing': 'Kabupaten_UnmetNeed_Spacing', 'Kabupaten_UnmetNeed_Limiting': 'Kabupaten_UnmetNeed_Limiting', 'Kabupaten_Jumlah_UnmetNeed': 'Kabupaten_Jumlah_UnmetNeed', 'Kabupaten_Persentase_UnmetNeed': 'Kabupaten_Persentase_UnmetNeed', });
lyr_BADUNGcopy_1.set('fieldImages', {'KDPPUM': 'TextEdit', 'NAMOBJ': 'TextEdit', 'REMARK': 'TextEdit', 'KDPBPS': 'TextEdit', 'FCODE': 'TextEdit', 'LUASWH': 'TextEdit', 'UUPP': 'TextEdit', 'SRS_ID': 'TextEdit', 'LCODE': 'TextEdit', 'METADATA': 'TextEdit', 'KDEBPS': 'TextEdit', 'KDEPUM': 'TextEdit', 'KDCBPS': 'TextEdit', 'KDCPUM': 'TextEdit', 'KDBBPS': 'TextEdit', 'KDBPUM': 'TextEdit', 'WADMKD': 'TextEdit', 'WIADKD': 'TextEdit', 'WADMKC': 'TextEdit', 'WIADKC': 'TextEdit', 'WADMKK': 'TextEdit', 'WIADKK': 'TextEdit', 'WADMPR': 'TextEdit', 'WIADPR': 'TextEdit', 'TIPADM': 'TextEdit', 'SHAPE_Leng': 'TextEdit', 'SHAPE_Area': 'TextEdit', 'jml_pus': 'TextEdit', });
lyr_BADUNG_2.set('fieldImages', {'KDPPUM': 'TextEdit', 'NAMOBJ': 'TextEdit', 'REMARK': 'TextEdit', 'KDPBPS': 'TextEdit', 'FCODE': 'TextEdit', 'LUASWH': 'TextEdit', 'UUPP': 'TextEdit', 'SRS_ID': 'TextEdit', 'LCODE': 'TextEdit', 'METADATA': 'TextEdit', 'KDEBPS': 'TextEdit', 'KDEPUM': 'TextEdit', 'KDCBPS': 'TextEdit', 'KDCPUM': 'TextEdit', 'KDBBPS': 'TextEdit', 'KDBPUM': 'TextEdit', 'WADMKD': 'TextEdit', 'WIADKD': 'TextEdit', 'WADMKC': 'TextEdit', 'WIADKC': 'TextEdit', 'WADMKK': 'TextEdit', 'WIADKK': 'TextEdit', 'WADMPR': 'TextEdit', 'WIADPR': 'TextEdit', 'TIPADM': 'TextEdit', 'SHAPE_Leng': 'TextEdit', 'SHAPE_Area': 'TextEdit', 'Badung_Kode_Kelurahan': 'TextEdit', 'Badung_Kode_Kecamatan': 'TextEdit', 'Badung_Jumlah_PUS': 'Range', 'Badung_UnmetNeed_Spacing': 'Range', 'Badung_UnmetNeed_Limiting': 'Range', 'Badung_Jumlah_UnmetNeed': 'TextEdit', 'Badung_Persentase_UnmetNeed': 'TextEdit', 'jml_pus': 'TextEdit', });
lyr_Bangli_3.set('fieldImages', {'KDPPUM': 'TextEdit', 'NAMOBJ': 'TextEdit', 'REMARK': 'TextEdit', 'KDPBPS': 'TextEdit', 'FCODE': 'TextEdit', 'LUASWH': 'TextEdit', 'UUPP': 'TextEdit', 'SRS_ID': 'TextEdit', 'LCODE': 'TextEdit', 'METADATA': 'TextEdit', 'KDEBPS': 'TextEdit', 'KDEPUM': 'TextEdit', 'KDCBPS': 'TextEdit', 'KDCPUM': 'TextEdit', 'KDBBPS': 'TextEdit', 'KDBPUM': 'TextEdit', 'WADMKD': 'TextEdit', 'WIADKD': 'TextEdit', 'WADMKC': 'TextEdit', 'WIADKC': 'TextEdit', 'WADMKK': 'TextEdit', 'WIADKK': 'TextEdit', 'WADMPR': 'TextEdit', 'WIADPR': 'TextEdit', 'TIPADM': 'TextEdit', 'SHAPE_Leng': 'TextEdit', 'SHAPE_Area': 'TextEdit', 'Bangli_Kode_Kelurahan': 'TextEdit', 'Bangli_Kode_Kecamatan': 'TextEdit', 'Bangli_Jumlah_PUS': 'Range', 'Bangli_UnmetNeed_Spacing': 'Range', 'Bangli_UnmetNeed_Limiting': 'Range', 'Bangli_Jumlah_UnmetNeed': 'Range', 'Bangli_Persentase_UnmetNeed': 'TextEdit', });
lyr_Buleleng_4.set('fieldImages', {'KDPPUM': 'TextEdit', 'NAMOBJ': 'TextEdit', 'REMARK': 'TextEdit', 'KDPBPS': 'TextEdit', 'FCODE': 'TextEdit', 'LUASWH': 'TextEdit', 'UUPP': 'TextEdit', 'SRS_ID': 'TextEdit', 'LCODE': 'TextEdit', 'METADATA': 'TextEdit', 'KDEBPS': 'TextEdit', 'KDEPUM': 'TextEdit', 'KDCBPS': 'TextEdit', 'KDCPUM': 'TextEdit', 'KDBBPS': 'TextEdit', 'KDBPUM': 'TextEdit', 'WADMKD': 'TextEdit', 'WIADKD': 'TextEdit', 'WADMKC': 'TextEdit', 'WIADKC': 'TextEdit', 'WADMKK': 'TextEdit', 'WIADKK': 'TextEdit', 'WADMPR': 'TextEdit', 'WIADPR': 'TextEdit', 'TIPADM': 'TextEdit', 'SHAPE_Leng': 'TextEdit', 'SHAPE_Area': 'TextEdit', 'Buleleng_Kode_Kelurahan': 'TextEdit', 'Buleleng_Kode_Kecamatan': 'TextEdit', 'Buleleng_Jumlah_PUS': 'TextEdit', 'Buleleng_UnmetNeed_Spacing': 'Range', 'Buleleng_UnmetNeed_Limiting': 'Range', 'Buleleng_Jumlah_UnmetNeed': 'Range', 'Buleleng_Persentase_UnmetNeed': 'TextEdit', });
lyr_GIANYAR_5.set('fieldImages', {'KDPPUM': 'TextEdit', 'NAMOBJ': 'TextEdit', 'REMARK': 'TextEdit', 'KDPBPS': 'TextEdit', 'FCODE': 'TextEdit', 'LUASWH': 'TextEdit', 'UUPP': 'TextEdit', 'SRS_ID': 'TextEdit', 'LCODE': 'TextEdit', 'METADATA': 'TextEdit', 'KDEBPS': 'TextEdit', 'KDEPUM': 'TextEdit', 'KDCBPS': 'TextEdit', 'KDCPUM': 'TextEdit', 'KDBBPS': 'TextEdit', 'KDBPUM': 'TextEdit', 'WADMKD': 'TextEdit', 'WIADKD': 'TextEdit', 'WADMKC': 'TextEdit', 'WIADKC': 'TextEdit', 'WADMKK': 'TextEdit', 'WIADKK': 'TextEdit', 'WADMPR': 'TextEdit', 'WIADPR': 'TextEdit', 'TIPADM': 'TextEdit', 'SHAPE_Leng': 'TextEdit', 'SHAPE_Area': 'TextEdit', 'Gianyar_Kode_Kelurahan': 'TextEdit', 'Gianyar_Kode_Kecamatan': 'TextEdit', 'Gianyar_Jumlah_PUS': 'Range', 'Gianyar_UnmetNeed_Spacing': 'Range', 'Gianyar_UnmetNeed_Limiting': 'Range', 'Gianyar_Jumlah_UnmetNeed': 'Range', 'Gianyar_Persentase_UnmetNeed': 'TextEdit', });
lyr_Jembrana_6.set('fieldImages', {'KDPPUM': 'TextEdit', 'NAMOBJ': 'TextEdit', 'REMARK': 'TextEdit', 'KDPBPS': 'TextEdit', 'FCODE': 'TextEdit', 'LUASWH': 'TextEdit', 'UUPP': 'TextEdit', 'SRS_ID': 'TextEdit', 'LCODE': 'TextEdit', 'METADATA': 'TextEdit', 'KDEBPS': 'TextEdit', 'KDEPUM': 'TextEdit', 'KDCBPS': 'TextEdit', 'KDCPUM': 'TextEdit', 'KDBBPS': 'TextEdit', 'KDBPUM': 'TextEdit', 'WADMKD': 'TextEdit', 'WIADKD': 'TextEdit', 'WADMKC': 'TextEdit', 'WIADKC': 'TextEdit', 'WADMKK': 'TextEdit', 'WIADKK': 'TextEdit', 'WADMPR': 'TextEdit', 'WIADPR': 'TextEdit', 'TIPADM': 'TextEdit', 'SHAPE_Leng': 'TextEdit', 'SHAPE_Area': 'TextEdit', 'Jembrana_Kode_Kelurahan': 'TextEdit', 'Jembrana_Kode_Kecamatan': 'ValueRelation', 'Jembrana_Jumlah_PUS': 'Range', 'Jembrana_UnmetNeed_Spacing': 'Range', 'Jembrana_UnmetNeed_Limiting': 'Range', 'Jembrana_Jumlah_UnmetNeed': 'Range', 'Jembrana_Persentase_UnmetNeed': 'TextEdit', });
lyr_Karangasem_7.set('fieldImages', {'KDPPUM': 'TextEdit', 'NAMOBJ': 'TextEdit', 'REMARK': 'TextEdit', 'KDPBPS': 'TextEdit', 'FCODE': 'TextEdit', 'LUASWH': 'TextEdit', 'UUPP': 'TextEdit', 'SRS_ID': 'TextEdit', 'LCODE': 'TextEdit', 'METADATA': 'TextEdit', 'KDEBPS': 'TextEdit', 'KDEPUM': 'TextEdit', 'KDCBPS': 'TextEdit', 'KDCPUM': 'TextEdit', 'KDBBPS': 'TextEdit', 'KDBPUM': 'TextEdit', 'WADMKD': 'TextEdit', 'WIADKD': 'TextEdit', 'WADMKC': 'TextEdit', 'WIADKC': 'TextEdit', 'WADMKK': 'TextEdit', 'WIADKK': 'TextEdit', 'WADMPR': 'TextEdit', 'WIADPR': 'TextEdit', 'TIPADM': 'TextEdit', 'SHAPE_Leng': 'TextEdit', 'SHAPE_Area': 'TextEdit', 'Karangasem_Kode_Kelurahan': 'TextEdit', 'Karangasem_Kode_Kecamatan': 'TextEdit', 'Karangasem_Jumlah_PUS': 'Range', 'Karangasem_UnmetNeed_Spacing': 'Range', 'Karangasem_UnmetNeed_Limiting': 'Range', 'Karangasem_Jumlah_UnmetNeed': 'Range', 'Karangasem_Persentase_UnmetNeed': 'TextEdit', });
lyr_Klungkung_8.set('fieldImages', {'KDPPUM': 'TextEdit', 'NAMOBJ': 'TextEdit', 'REMARK': 'TextEdit', 'KDPBPS': 'TextEdit', 'FCODE': 'TextEdit', 'LUASWH': 'TextEdit', 'UUPP': 'TextEdit', 'SRS_ID': 'TextEdit', 'LCODE': 'TextEdit', 'METADATA': 'TextEdit', 'KDEBPS': 'TextEdit', 'KDEPUM': 'TextEdit', 'KDCBPS': 'TextEdit', 'KDCPUM': 'TextEdit', 'KDBBPS': 'TextEdit', 'KDBPUM': 'TextEdit', 'WADMKD': 'TextEdit', 'WIADKD': 'TextEdit', 'WADMKC': 'TextEdit', 'WIADKC': 'TextEdit', 'WADMKK': 'TextEdit', 'WIADKK': 'TextEdit', 'WADMPR': 'TextEdit', 'WIADPR': 'TextEdit', 'TIPADM': 'TextEdit', 'SHAPE_Leng': 'TextEdit', 'SHAPE_Area': 'TextEdit', 'Klungkung_Kode_Kelurahan': 'TextEdit', 'Klungkung_Kode_Kecamatan': 'TextEdit', 'Klungkung_Jumlah_PUS': 'Range', 'Klungkung_UnmetNeed_Spacing': 'Range', 'Klungkung_UnmetNeed_Limiting': 'Range', 'Klungkung_Jumlah_UnmetNeed': 'Range', 'Klungkung_Persentase_UnmetNeed': 'TextEdit', });
lyr_Tabanan_9.set('fieldImages', {'KDPPUM': 'TextEdit', 'NAMOBJ': 'TextEdit', 'REMARK': 'TextEdit', 'KDPBPS': 'TextEdit', 'FCODE': 'TextEdit', 'LUASWH': 'TextEdit', 'UUPP': 'TextEdit', 'SRS_ID': 'TextEdit', 'LCODE': 'TextEdit', 'METADATA': 'TextEdit', 'KDEBPS': 'TextEdit', 'KDEPUM': 'TextEdit', 'KDCBPS': 'TextEdit', 'KDCPUM': 'TextEdit', 'KDBBPS': 'TextEdit', 'KDBPUM': 'TextEdit', 'WADMKD': 'TextEdit', 'WIADKD': 'TextEdit', 'WADMKC': 'TextEdit', 'WIADKC': 'TextEdit', 'WADMKK': 'TextEdit', 'WIADKK': 'TextEdit', 'WADMPR': 'TextEdit', 'WIADPR': 'TextEdit', 'TIPADM': 'TextEdit', 'SHAPE_Leng': 'TextEdit', 'SHAPE_Area': 'TextEdit', 'Tabanan_Kode_Kelurahan': 'TextEdit', 'Tabanan_Kode_Kecamatan': 'TextEdit', 'Tabanan_Jumlah_PUS': 'Range', 'Tabanan_UnmetNeed_Spacing': 'Range', 'Tabanan_UnmetNeed_Limiting': 'Range', 'Tabanan_Jumlah_UnmetNeed': 'Range', 'Tabanan_Persentase_UnmetNeed': 'TextEdit', });
lyr_Denpasar_10.set('fieldImages', {'KDPPUM': 'TextEdit', 'NAMOBJ': 'TextEdit', 'REMARK': 'TextEdit', 'KDPBPS': 'TextEdit', 'FCODE': 'TextEdit', 'LUASWH': 'TextEdit', 'UUPP': 'TextEdit', 'SRS_ID': 'TextEdit', 'LCODE': 'TextEdit', 'METADATA': 'TextEdit', 'KDEBPS': 'TextEdit', 'KDEPUM': 'TextEdit', 'KDCBPS': 'TextEdit', 'KDCPUM': 'TextEdit', 'KDBBPS': 'TextEdit', 'KDBPUM': 'TextEdit', 'WADMKD': 'TextEdit', 'WIADKD': 'TextEdit', 'WADMKC': 'TextEdit', 'WIADKC': 'TextEdit', 'WADMKK': 'TextEdit', 'WIADKK': 'TextEdit', 'WADMPR': 'TextEdit', 'WIADPR': 'TextEdit', 'TIPADM': 'TextEdit', 'SHAPE_Leng': 'TextEdit', 'SHAPE_Area': 'TextEdit', 'Denpasar_Kode_Kelurahan': 'TextEdit', 'Denpasar_Kode_Kecamatan': 'TextEdit', 'Denpasar_Jumlah_PUS': 'Range', 'Denpasar_UnmetNeed_Spacing': 'Range', 'Denpasar_UnmetNeed_Limiting': 'Range', 'Denpasar_Jumlah_UnmetNeed': 'Range', 'Denpasar_Persentase_UnmetNeed': 'TextEdit', });
lyr_KecBadung_11.set('fieldImages', {'KDPPUM': 'TextEdit', 'NAMOBJ': 'TextEdit', 'REMARK': 'TextEdit', 'KDPBPS': 'TextEdit', 'FCODE': 'TextEdit', 'LUASWH': 'TextEdit', 'UUPP': 'TextEdit', 'SRS_ID': 'TextEdit', 'LCODE': 'TextEdit', 'METADATA': 'TextEdit', 'KDEBPS': 'TextEdit', 'KDEPUM': 'TextEdit', 'KDCBPS': 'TextEdit', 'KDCPUM': 'TextEdit', 'KDBBPS': 'TextEdit', 'KDBPUM': 'TextEdit', 'WADMKD': 'TextEdit', 'WIADKD': 'TextEdit', 'WADMKC': 'TextEdit', 'WIADKC': 'TextEdit', 'WADMKK': 'TextEdit', 'WIADKK': 'TextEdit', 'WADMPR': 'TextEdit', 'WIADPR': 'TextEdit', 'TIPADM': 'TextEdit', 'SHAPE_Leng': 'TextEdit', 'SHAPE_Area': 'TextEdit', 'KecBadung_Kode_Kecamatan': 'TextEdit', 'KecBadung_Kode_Kabupaten': 'TextEdit', 'KecBadung_Jumlah_PUS': 'Range', 'KecBadung_UnmetNeed_Spacing': 'Range', 'KecBadung_UnmetNeed_Limiting': 'Range', 'KecBadung_Jumlah_UnmetNeed': 'Range', 'KecBadung_Persentase_UnmetNeed': 'TextEdit', });
lyr_KecBangli_12.set('fieldImages', {'KDPPUM': 'TextEdit', 'NAMOBJ': 'TextEdit', 'REMARK': 'TextEdit', 'KDPBPS': 'TextEdit', 'FCODE': 'TextEdit', 'LUASWH': 'TextEdit', 'UUPP': 'TextEdit', 'SRS_ID': 'TextEdit', 'LCODE': 'TextEdit', 'METADATA': 'TextEdit', 'KDEBPS': 'TextEdit', 'KDEPUM': 'TextEdit', 'KDCBPS': 'TextEdit', 'KDCPUM': 'TextEdit', 'KDBBPS': 'TextEdit', 'KDBPUM': 'TextEdit', 'WADMKD': 'TextEdit', 'WIADKD': 'TextEdit', 'WADMKC': 'TextEdit', 'WIADKC': 'TextEdit', 'WADMKK': 'TextEdit', 'WIADKK': 'TextEdit', 'WADMPR': 'TextEdit', 'WIADPR': 'TextEdit', 'TIPADM': 'TextEdit', 'SHAPE_Leng': 'TextEdit', 'SHAPE_Area': 'TextEdit', 'KecBangli_Kode_Kecamatan': 'TextEdit', 'KecBangli_Kode_Kabupaten': 'TextEdit', 'KecBangli_Jumlah_PUS': 'Range', 'KecBangli_UnmetNeed_Spacing': 'Range', 'KecBangli_UnmetNeed_Limiting': 'Range', 'KecBangli_Jumlah_UnmetNeed': 'Range', 'KecBangli_Persentase_UnmetNeed': 'TextEdit', });
lyr_KecBuleleng_13.set('fieldImages', {'KDPPUM': 'TextEdit', 'NAMOBJ': 'TextEdit', 'REMARK': 'TextEdit', 'KDPBPS': 'TextEdit', 'FCODE': 'TextEdit', 'LUASWH': 'TextEdit', 'UUPP': 'TextEdit', 'SRS_ID': 'TextEdit', 'LCODE': 'TextEdit', 'METADATA': 'TextEdit', 'KDEBPS': 'TextEdit', 'KDEPUM': 'TextEdit', 'KDCBPS': 'TextEdit', 'KDCPUM': 'TextEdit', 'KDBBPS': 'TextEdit', 'KDBPUM': 'TextEdit', 'WADMKD': 'TextEdit', 'WIADKD': 'TextEdit', 'WADMKC': 'TextEdit', 'WIADKC': 'TextEdit', 'WADMKK': 'TextEdit', 'WIADKK': 'TextEdit', 'WADMPR': 'TextEdit', 'WIADPR': 'TextEdit', 'TIPADM': 'TextEdit', 'SHAPE_Leng': 'TextEdit', 'SHAPE_Area': 'TextEdit', 'KecBuleleng_Kode_Kecamatan': 'TextEdit', 'KecBuleleng_Kode_Kabupaten': 'TextEdit', 'KecBuleleng_Jumlah_PUS': 'Range', 'KecBuleleng_UnmetNeed_Spacing': 'Range', 'KecBuleleng_UnmetNeed_Limiting': 'Range', 'KecBuleleng_Jumlah_UnmetNeed': 'Range', 'KecBuleleng_Persentase_UnmetNeed': 'TextEdit', });
lyr_KecGianyar_14.set('fieldImages', {'KDPPUM': 'TextEdit', 'NAMOBJ': 'TextEdit', 'REMARK': 'TextEdit', 'KDPBPS': 'TextEdit', 'FCODE': 'TextEdit', 'LUASWH': 'TextEdit', 'UUPP': 'TextEdit', 'SRS_ID': 'TextEdit', 'LCODE': 'TextEdit', 'METADATA': 'TextEdit', 'KDEBPS': 'TextEdit', 'KDEPUM': 'TextEdit', 'KDCBPS': 'TextEdit', 'KDCPUM': 'TextEdit', 'KDBBPS': 'TextEdit', 'KDBPUM': 'TextEdit', 'WADMKD': 'TextEdit', 'WIADKD': 'TextEdit', 'WADMKC': 'TextEdit', 'WIADKC': 'TextEdit', 'WADMKK': 'TextEdit', 'WIADKK': 'TextEdit', 'WADMPR': 'TextEdit', 'WIADPR': 'TextEdit', 'TIPADM': 'TextEdit', 'SHAPE_Leng': 'TextEdit', 'SHAPE_Area': 'TextEdit', 'KecGianyar_Kode_Kecamatan': 'TextEdit', 'KecGianyar_Kode_Kabupaten': 'TextEdit', 'KecGianyar_Jumlah_PUS': 'Range', 'KecGianyar_UnmetNeed_Spacing': 'Range', 'KecGianyar_UnmetNeed_Limiting': 'Range', 'KecGianyar_Jumlah_UnmetNeed': 'Range', 'KecGianyar_Persentase_UnmetNeed': 'TextEdit', });
lyr_KecJembrana_15.set('fieldImages', {'KDPPUM': 'TextEdit', 'NAMOBJ': 'TextEdit', 'REMARK': 'TextEdit', 'KDPBPS': 'TextEdit', 'FCODE': 'TextEdit', 'LUASWH': 'TextEdit', 'UUPP': 'TextEdit', 'SRS_ID': 'TextEdit', 'LCODE': 'TextEdit', 'METADATA': 'TextEdit', 'KDEBPS': 'TextEdit', 'KDEPUM': 'TextEdit', 'KDCBPS': 'TextEdit', 'KDCPUM': 'TextEdit', 'KDBBPS': 'TextEdit', 'KDBPUM': 'TextEdit', 'WADMKD': 'TextEdit', 'WIADKD': 'TextEdit', 'WADMKC': 'TextEdit', 'WIADKC': 'TextEdit', 'WADMKK': 'TextEdit', 'WIADKK': 'TextEdit', 'WADMPR': 'TextEdit', 'WIADPR': 'TextEdit', 'TIPADM': 'TextEdit', 'SHAPE_Leng': 'TextEdit', 'SHAPE_Area': 'TextEdit', 'KecJembrana_Kode_Kecamatan': 'TextEdit', 'KecJembrana_Kode_Kabupaten': 'TextEdit', 'KecJembrana_Jumlah_PUS': 'Range', 'KecJembrana_UnmetNeed_Spacing': 'Range', 'KecJembrana_UnmetNeed_Limiting': 'Range', 'KecJembrana_Jumlah_UnmetNeed': 'Range', 'KecJembrana_Persentase_UnmetNeed': 'TextEdit', });
lyr_KecKarangasem_16.set('fieldImages', {'KDPPUM': 'TextEdit', 'NAMOBJ': 'TextEdit', 'REMARK': 'TextEdit', 'KDPBPS': 'TextEdit', 'FCODE': 'TextEdit', 'LUASWH': 'TextEdit', 'UUPP': 'TextEdit', 'SRS_ID': 'TextEdit', 'LCODE': 'TextEdit', 'METADATA': 'TextEdit', 'KDEBPS': 'TextEdit', 'KDEPUM': 'TextEdit', 'KDCBPS': 'TextEdit', 'KDCPUM': 'TextEdit', 'KDBBPS': 'TextEdit', 'KDBPUM': 'TextEdit', 'WADMKD': 'TextEdit', 'WIADKD': 'TextEdit', 'WADMKC': 'TextEdit', 'WIADKC': 'TextEdit', 'WADMKK': 'TextEdit', 'WIADKK': 'TextEdit', 'WADMPR': 'TextEdit', 'WIADPR': 'TextEdit', 'TIPADM': 'TextEdit', 'SHAPE_Leng': 'TextEdit', 'SHAPE_Area': 'TextEdit', 'KecKarangasem_Kode_Kecamatan': 'TextEdit', 'KecKarangasem_Kode_Kabupaten': 'TextEdit', 'KecKarangasem_Jumlah_PUS': 'Range', 'KecKarangasem_UnmetNeed_Spacing': 'Range', 'KecKarangasem_UnmetNeed_Limiting': 'Range', 'KecKarangasem_Jumlah_UnmetNeed': 'Range', 'KecKarangasem_Persentase_UnmetNeed': 'TextEdit', });
lyr_KecKlungkung_17.set('fieldImages', {'KDPPUM': 'TextEdit', 'NAMOBJ': 'TextEdit', 'REMARK': 'TextEdit', 'KDPBPS': 'TextEdit', 'FCODE': 'TextEdit', 'LUASWH': 'TextEdit', 'UUPP': 'TextEdit', 'SRS_ID': 'TextEdit', 'LCODE': 'TextEdit', 'METADATA': 'TextEdit', 'KDEBPS': 'TextEdit', 'KDEPUM': 'TextEdit', 'KDCBPS': 'TextEdit', 'KDCPUM': 'TextEdit', 'KDBBPS': 'TextEdit', 'KDBPUM': 'TextEdit', 'WADMKD': 'TextEdit', 'WIADKD': 'TextEdit', 'WADMKC': 'TextEdit', 'WIADKC': 'TextEdit', 'WADMKK': 'TextEdit', 'WIADKK': 'TextEdit', 'WADMPR': 'TextEdit', 'WIADPR': 'TextEdit', 'TIPADM': 'TextEdit', 'SHAPE_Leng': 'TextEdit', 'SHAPE_Area': 'TextEdit', 'KecKlungkung_Kode_Kecamatan': 'TextEdit', 'KecKlungkung_Kode_Kabupaten': 'TextEdit', 'KecKlungkung_Jumlah_PUS': 'Range', 'KecKlungkung_UnmetNeed_Spacing': 'Range', 'KecKlungkung_UnmetNeed_Limiting': 'Range', 'KecKlungkung_Jumlah_UnmetNeed': 'Range', 'KecKlungkung_Persentase_UnmetNeed': 'TextEdit', });
lyr_KecTabanan_18.set('fieldImages', {'KDPPUM': 'TextEdit', 'NAMOBJ': 'TextEdit', 'REMARK': 'TextEdit', 'KDPBPS': 'TextEdit', 'FCODE': 'TextEdit', 'LUASWH': 'TextEdit', 'UUPP': 'TextEdit', 'SRS_ID': 'TextEdit', 'LCODE': 'TextEdit', 'METADATA': 'TextEdit', 'KDEBPS': 'TextEdit', 'KDEPUM': 'TextEdit', 'KDCBPS': 'TextEdit', 'KDCPUM': 'TextEdit', 'KDBBPS': 'TextEdit', 'KDBPUM': 'TextEdit', 'WADMKD': 'TextEdit', 'WIADKD': 'TextEdit', 'WADMKC': 'TextEdit', 'WIADKC': 'TextEdit', 'WADMKK': 'TextEdit', 'WIADKK': 'TextEdit', 'WADMPR': 'TextEdit', 'WIADPR': 'TextEdit', 'TIPADM': 'TextEdit', 'SHAPE_Leng': 'TextEdit', 'SHAPE_Area': 'TextEdit', 'KecTabanan_Kode_Kecamatan': 'TextEdit', 'KecTabanan_Kode_Kabupaten': 'TextEdit', 'KecTabanan_Jumlah_PUS': 'Range', 'KecTabanan_UnmetNeed_Spacing': 'Range', 'KecTabanan_UnmetNeed_Limiting': 'Range', 'KecTabanan_Jumlah_UnmetNeed': 'Range', 'KecTabanan_Persentase_UnmetNeed': 'TextEdit', });
lyr_KecDenpasar_19.set('fieldImages', {'KDPPUM': 'TextEdit', 'NAMOBJ': 'TextEdit', 'REMARK': 'TextEdit', 'KDPBPS': 'TextEdit', 'FCODE': 'TextEdit', 'LUASWH': 'TextEdit', 'UUPP': 'TextEdit', 'SRS_ID': 'TextEdit', 'LCODE': 'TextEdit', 'METADATA': 'TextEdit', 'KDEBPS': 'TextEdit', 'KDEPUM': 'TextEdit', 'KDCBPS': 'TextEdit', 'KDCPUM': 'TextEdit', 'KDBBPS': 'TextEdit', 'KDBPUM': 'TextEdit', 'WADMKD': 'TextEdit', 'WIADKD': 'TextEdit', 'WADMKC': 'TextEdit', 'WIADKC': 'TextEdit', 'WADMKK': 'TextEdit', 'WIADKK': 'TextEdit', 'WADMPR': 'TextEdit', 'WIADPR': 'TextEdit', 'TIPADM': 'TextEdit', 'SHAPE_Leng': 'TextEdit', 'SHAPE_Area': 'TextEdit', 'KecDenpasar_Kode_Kecamatan': 'TextEdit', 'KecDenpasar_Kode_Kabupaten': 'TextEdit', 'KecDenpasar_Jumlah_PUS': 'Range', 'KecDenpasar_UnmetNeed_Spacing': 'Range', 'KecDenpasar_UnmetNeed_Limiting': 'Range', 'KecDenpasar_Jumlah_UnmetNeed': 'Range', 'KecDenpasar_Persentase_UnmetNeed': 'TextEdit', });
lyr_BALI_20.set('fieldImages', {'PROVINSI': 'TextEdit', 'KABKOT': 'TextEdit', 'KECAMATAN': 'TextEdit', 'KODE': 'TextEdit', 'DESA': 'TextEdit', 'Kabupaten_Kode_Kabupaten': 'TextEdit', 'Kabupaten_Jumlah_PUS': 'Range', 'Kabupaten_UnmetNeed_Spacing': 'Range', 'Kabupaten_UnmetNeed_Limiting': 'Range', 'Kabupaten_Jumlah_UnmetNeed': 'Range', 'Kabupaten_Persentase_UnmetNeed': 'TextEdit', });
lyr_BADUNGcopy_1.set('fieldLabels', {'KDPPUM': 'inline label - visible with data', 'NAMOBJ': 'inline label - visible with data', 'REMARK': 'inline label - visible with data', 'KDPBPS': 'inline label - visible with data', 'FCODE': 'inline label - visible with data', 'LUASWH': 'inline label - visible with data', 'UUPP': 'inline label - visible with data', 'SRS_ID': 'inline label - visible with data', 'LCODE': 'inline label - visible with data', 'METADATA': 'inline label - visible with data', 'KDEBPS': 'inline label - visible with data', 'KDEPUM': 'inline label - visible with data', 'KDCBPS': 'inline label - visible with data', 'KDCPUM': 'inline label - visible with data', 'KDBBPS': 'inline label - visible with data', 'KDBPUM': 'inline label - visible with data', 'WADMKD': 'inline label - visible with data', 'WIADKD': 'inline label - visible with data', 'WADMKC': 'inline label - visible with data', 'WIADKC': 'inline label - visible with data', 'WADMKK': 'inline label - visible with data', 'WIADKK': 'inline label - visible with data', 'WADMPR': 'inline label - visible with data', 'WIADPR': 'inline label - visible with data', 'TIPADM': 'inline label - visible with data', 'SHAPE_Leng': 'inline label - visible with data', 'SHAPE_Area': 'inline label - visible with data', 'jml_pus': 'inline label - visible with data', });
lyr_BADUNG_2.set('fieldLabels', {'KDPPUM': 'inline label - visible with data', 'NAMOBJ': 'inline label - visible with data', 'REMARK': 'inline label - visible with data', 'KDPBPS': 'inline label - visible with data', 'FCODE': 'inline label - visible with data', 'LUASWH': 'inline label - visible with data', 'UUPP': 'inline label - visible with data', 'SRS_ID': 'inline label - visible with data', 'LCODE': 'inline label - visible with data', 'METADATA': 'inline label - visible with data', 'KDEBPS': 'inline label - visible with data', 'KDEPUM': 'inline label - visible with data', 'KDCBPS': 'inline label - visible with data', 'KDCPUM': 'inline label - visible with data', 'KDBBPS': 'inline label - visible with data', 'KDBPUM': 'inline label - visible with data', 'WADMKD': 'inline label - visible with data', 'WIADKD': 'inline label - visible with data', 'WADMKC': 'inline label - visible with data', 'WIADKC': 'inline label - visible with data', 'WADMKK': 'inline label - visible with data', 'WIADKK': 'inline label - visible with data', 'WADMPR': 'inline label - visible with data', 'WIADPR': 'inline label - visible with data', 'TIPADM': 'inline label - visible with data', 'SHAPE_Leng': 'inline label - visible with data', 'SHAPE_Area': 'inline label - visible with data', 'Badung_Kode_Kelurahan': 'inline label - visible with data', 'Badung_Kode_Kecamatan': 'inline label - visible with data', 'Badung_Jumlah_PUS': 'inline label - visible with data', 'Badung_UnmetNeed_Spacing': 'inline label - visible with data', 'Badung_UnmetNeed_Limiting': 'inline label - visible with data', 'Badung_Jumlah_UnmetNeed': 'inline label - visible with data', 'Badung_Persentase_UnmetNeed': 'inline label - visible with data', 'jml_pus': 'inline label - visible with data', });
lyr_Bangli_3.set('fieldLabels', {'KDPPUM': 'inline label - visible with data', 'NAMOBJ': 'inline label - visible with data', 'REMARK': 'inline label - visible with data', 'KDPBPS': 'inline label - visible with data', 'FCODE': 'inline label - visible with data', 'LUASWH': 'inline label - visible with data', 'UUPP': 'inline label - visible with data', 'SRS_ID': 'inline label - visible with data', 'LCODE': 'inline label - visible with data', 'METADATA': 'inline label - visible with data', 'KDEBPS': 'inline label - visible with data', 'KDEPUM': 'inline label - visible with data', 'KDCBPS': 'inline label - visible with data', 'KDCPUM': 'inline label - visible with data', 'KDBBPS': 'inline label - visible with data', 'KDBPUM': 'inline label - visible with data', 'WADMKD': 'inline label - visible with data', 'WIADKD': 'inline label - visible with data', 'WADMKC': 'inline label - visible with data', 'WIADKC': 'inline label - visible with data', 'WADMKK': 'inline label - visible with data', 'WIADKK': 'inline label - visible with data', 'WADMPR': 'inline label - visible with data', 'WIADPR': 'inline label - visible with data', 'TIPADM': 'inline label - visible with data', 'SHAPE_Leng': 'inline label - visible with data', 'SHAPE_Area': 'inline label - visible with data', 'Bangli_Kode_Kelurahan': 'inline label - visible with data', 'Bangli_Kode_Kecamatan': 'inline label - visible with data', 'Bangli_Jumlah_PUS': 'inline label - visible with data', 'Bangli_UnmetNeed_Spacing': 'inline label - visible with data', 'Bangli_UnmetNeed_Limiting': 'inline label - visible with data', 'Bangli_Jumlah_UnmetNeed': 'inline label - visible with data', 'Bangli_Persentase_UnmetNeed': 'inline label - visible with data', });
lyr_Buleleng_4.set('fieldLabels', {'KDPPUM': 'inline label - visible with data', 'NAMOBJ': 'inline label - visible with data', 'REMARK': 'inline label - visible with data', 'KDPBPS': 'inline label - visible with data', 'FCODE': 'inline label - visible with data', 'LUASWH': 'inline label - visible with data', 'UUPP': 'inline label - visible with data', 'SRS_ID': 'inline label - visible with data', 'LCODE': 'inline label - visible with data', 'METADATA': 'inline label - visible with data', 'KDEBPS': 'inline label - visible with data', 'KDEPUM': 'inline label - visible with data', 'KDCBPS': 'inline label - visible with data', 'KDCPUM': 'inline label - visible with data', 'KDBBPS': 'inline label - visible with data', 'KDBPUM': 'inline label - visible with data', 'WADMKD': 'inline label - visible with data', 'WIADKD': 'inline label - visible with data', 'WADMKC': 'inline label - visible with data', 'WIADKC': 'inline label - visible with data', 'WADMKK': 'inline label - visible with data', 'WIADKK': 'inline label - visible with data', 'WADMPR': 'inline label - visible with data', 'WIADPR': 'inline label - visible with data', 'TIPADM': 'inline label - visible with data', 'SHAPE_Leng': 'inline label - visible with data', 'SHAPE_Area': 'inline label - visible with data', 'Buleleng_Kode_Kelurahan': 'inline label - visible with data', 'Buleleng_Kode_Kecamatan': 'inline label - visible with data', 'Buleleng_Jumlah_PUS': 'inline label - visible with data', 'Buleleng_UnmetNeed_Spacing': 'inline label - visible with data', 'Buleleng_UnmetNeed_Limiting': 'inline label - visible with data', 'Buleleng_Jumlah_UnmetNeed': 'inline label - visible with data', 'Buleleng_Persentase_UnmetNeed': 'inline label - visible with data', });
lyr_GIANYAR_5.set('fieldLabels', {'KDPPUM': 'inline label - visible with data', 'NAMOBJ': 'inline label - visible with data', 'REMARK': 'inline label - visible with data', 'KDPBPS': 'inline label - visible with data', 'FCODE': 'inline label - visible with data', 'LUASWH': 'inline label - visible with data', 'UUPP': 'inline label - visible with data', 'SRS_ID': 'inline label - visible with data', 'LCODE': 'inline label - visible with data', 'METADATA': 'inline label - visible with data', 'KDEBPS': 'inline label - visible with data', 'KDEPUM': 'inline label - visible with data', 'KDCBPS': 'inline label - visible with data', 'KDCPUM': 'inline label - visible with data', 'KDBBPS': 'inline label - visible with data', 'KDBPUM': 'inline label - visible with data', 'WADMKD': 'inline label - visible with data', 'WIADKD': 'inline label - visible with data', 'WADMKC': 'inline label - visible with data', 'WIADKC': 'inline label - visible with data', 'WADMKK': 'inline label - visible with data', 'WIADKK': 'inline label - visible with data', 'WADMPR': 'inline label - visible with data', 'WIADPR': 'inline label - visible with data', 'TIPADM': 'inline label - visible with data', 'SHAPE_Leng': 'inline label - visible with data', 'SHAPE_Area': 'inline label - visible with data', 'Gianyar_Kode_Kelurahan': 'inline label - visible with data', 'Gianyar_Kode_Kecamatan': 'inline label - visible with data', 'Gianyar_Jumlah_PUS': 'inline label - visible with data', 'Gianyar_UnmetNeed_Spacing': 'inline label - visible with data', 'Gianyar_UnmetNeed_Limiting': 'inline label - visible with data', 'Gianyar_Jumlah_UnmetNeed': 'inline label - visible with data', 'Gianyar_Persentase_UnmetNeed': 'inline label - visible with data', });
lyr_Jembrana_6.set('fieldLabels', {'KDPPUM': 'inline label - visible with data', 'NAMOBJ': 'inline label - visible with data', 'REMARK': 'inline label - visible with data', 'KDPBPS': 'inline label - visible with data', 'FCODE': 'inline label - visible with data', 'LUASWH': 'inline label - visible with data', 'UUPP': 'inline label - visible with data', 'SRS_ID': 'inline label - visible with data', 'LCODE': 'inline label - visible with data', 'METADATA': 'inline label - visible with data', 'KDEBPS': 'inline label - visible with data', 'KDEPUM': 'inline label - visible with data', 'KDCBPS': 'inline label - visible with data', 'KDCPUM': 'inline label - visible with data', 'KDBBPS': 'inline label - visible with data', 'KDBPUM': 'inline label - visible with data', 'WADMKD': 'inline label - visible with data', 'WIADKD': 'inline label - visible with data', 'WADMKC': 'inline label - visible with data', 'WIADKC': 'inline label - visible with data', 'WADMKK': 'inline label - visible with data', 'WIADKK': 'inline label - visible with data', 'WADMPR': 'inline label - visible with data', 'WIADPR': 'inline label - visible with data', 'TIPADM': 'inline label - visible with data', 'SHAPE_Leng': 'inline label - visible with data', 'SHAPE_Area': 'inline label - visible with data', 'Jembrana_Kode_Kelurahan': 'inline label - visible with data', 'Jembrana_Kode_Kecamatan': 'inline label - visible with data', 'Jembrana_Jumlah_PUS': 'inline label - visible with data', 'Jembrana_UnmetNeed_Spacing': 'inline label - visible with data', 'Jembrana_UnmetNeed_Limiting': 'inline label - visible with data', 'Jembrana_Jumlah_UnmetNeed': 'inline label - visible with data', 'Jembrana_Persentase_UnmetNeed': 'inline label - visible with data', });
lyr_Karangasem_7.set('fieldLabels', {'KDPPUM': 'inline label - visible with data', 'NAMOBJ': 'inline label - visible with data', 'REMARK': 'inline label - visible with data', 'KDPBPS': 'inline label - visible with data', 'FCODE': 'inline label - visible with data', 'LUASWH': 'inline label - visible with data', 'UUPP': 'inline label - visible with data', 'SRS_ID': 'inline label - visible with data', 'LCODE': 'inline label - visible with data', 'METADATA': 'inline label - visible with data', 'KDEBPS': 'inline label - visible with data', 'KDEPUM': 'inline label - visible with data', 'KDCBPS': 'inline label - visible with data', 'KDCPUM': 'inline label - visible with data', 'KDBBPS': 'inline label - visible with data', 'KDBPUM': 'inline label - visible with data', 'WADMKD': 'inline label - visible with data', 'WIADKD': 'inline label - visible with data', 'WADMKC': 'inline label - visible with data', 'WIADKC': 'inline label - visible with data', 'WADMKK': 'inline label - visible with data', 'WIADKK': 'inline label - visible with data', 'WADMPR': 'inline label - visible with data', 'WIADPR': 'inline label - visible with data', 'TIPADM': 'inline label - visible with data', 'SHAPE_Leng': 'inline label - visible with data', 'SHAPE_Area': 'inline label - visible with data', 'Karangasem_Kode_Kelurahan': 'inline label - visible with data', 'Karangasem_Kode_Kecamatan': 'inline label - visible with data', 'Karangasem_Jumlah_PUS': 'inline label - visible with data', 'Karangasem_UnmetNeed_Spacing': 'inline label - visible with data', 'Karangasem_UnmetNeed_Limiting': 'inline label - visible with data', 'Karangasem_Jumlah_UnmetNeed': 'inline label - visible with data', 'Karangasem_Persentase_UnmetNeed': 'inline label - visible with data', });
lyr_Klungkung_8.set('fieldLabels', {'KDPPUM': 'inline label - visible with data', 'NAMOBJ': 'inline label - visible with data', 'REMARK': 'inline label - visible with data', 'KDPBPS': 'inline label - visible with data', 'FCODE': 'inline label - visible with data', 'LUASWH': 'inline label - visible with data', 'UUPP': 'inline label - visible with data', 'SRS_ID': 'inline label - visible with data', 'LCODE': 'inline label - visible with data', 'METADATA': 'inline label - visible with data', 'KDEBPS': 'inline label - visible with data', 'KDEPUM': 'inline label - visible with data', 'KDCBPS': 'inline label - visible with data', 'KDCPUM': 'inline label - visible with data', 'KDBBPS': 'inline label - visible with data', 'KDBPUM': 'inline label - visible with data', 'WADMKD': 'inline label - visible with data', 'WIADKD': 'inline label - visible with data', 'WADMKC': 'inline label - visible with data', 'WIADKC': 'inline label - visible with data', 'WADMKK': 'inline label - visible with data', 'WIADKK': 'inline label - visible with data', 'WADMPR': 'inline label - visible with data', 'WIADPR': 'inline label - visible with data', 'TIPADM': 'inline label - visible with data', 'SHAPE_Leng': 'inline label - visible with data', 'SHAPE_Area': 'inline label - visible with data', 'Klungkung_Kode_Kelurahan': 'inline label - visible with data', 'Klungkung_Kode_Kecamatan': 'inline label - visible with data', 'Klungkung_Jumlah_PUS': 'inline label - visible with data', 'Klungkung_UnmetNeed_Spacing': 'inline label - visible with data', 'Klungkung_UnmetNeed_Limiting': 'inline label - visible with data', 'Klungkung_Jumlah_UnmetNeed': 'inline label - visible with data', 'Klungkung_Persentase_UnmetNeed': 'inline label - visible with data', });
lyr_Tabanan_9.set('fieldLabels', {'KDPPUM': 'inline label - visible with data', 'NAMOBJ': 'inline label - visible with data', 'REMARK': 'inline label - visible with data', 'KDPBPS': 'inline label - visible with data', 'FCODE': 'inline label - visible with data', 'LUASWH': 'inline label - visible with data', 'UUPP': 'inline label - visible with data', 'SRS_ID': 'inline label - visible with data', 'LCODE': 'inline label - visible with data', 'METADATA': 'inline label - visible with data', 'KDEBPS': 'inline label - visible with data', 'KDEPUM': 'inline label - visible with data', 'KDCBPS': 'inline label - visible with data', 'KDCPUM': 'inline label - visible with data', 'KDBBPS': 'inline label - visible with data', 'KDBPUM': 'inline label - visible with data', 'WADMKD': 'inline label - visible with data', 'WIADKD': 'inline label - visible with data', 'WADMKC': 'inline label - visible with data', 'WIADKC': 'inline label - visible with data', 'WADMKK': 'inline label - visible with data', 'WIADKK': 'inline label - visible with data', 'WADMPR': 'inline label - visible with data', 'WIADPR': 'inline label - visible with data', 'TIPADM': 'inline label - visible with data', 'SHAPE_Leng': 'inline label - visible with data', 'SHAPE_Area': 'inline label - visible with data', 'Tabanan_Kode_Kelurahan': 'inline label - visible with data', 'Tabanan_Kode_Kecamatan': 'inline label - visible with data', 'Tabanan_Jumlah_PUS': 'inline label - visible with data', 'Tabanan_UnmetNeed_Spacing': 'inline label - visible with data', 'Tabanan_UnmetNeed_Limiting': 'inline label - visible with data', 'Tabanan_Jumlah_UnmetNeed': 'inline label - visible with data', 'Tabanan_Persentase_UnmetNeed': 'inline label - visible with data', });
lyr_Denpasar_10.set('fieldLabels', {'KDPPUM': 'inline label - visible with data', 'NAMOBJ': 'inline label - visible with data', 'REMARK': 'inline label - visible with data', 'KDPBPS': 'inline label - visible with data', 'FCODE': 'inline label - visible with data', 'LUASWH': 'inline label - visible with data', 'UUPP': 'inline label - visible with data', 'SRS_ID': 'inline label - visible with data', 'LCODE': 'inline label - visible with data', 'METADATA': 'inline label - visible with data', 'KDEBPS': 'inline label - visible with data', 'KDEPUM': 'inline label - visible with data', 'KDCBPS': 'inline label - visible with data', 'KDCPUM': 'inline label - visible with data', 'KDBBPS': 'inline label - visible with data', 'KDBPUM': 'inline label - visible with data', 'WADMKD': 'inline label - visible with data', 'WIADKD': 'inline label - visible with data', 'WADMKC': 'inline label - visible with data', 'WIADKC': 'inline label - visible with data', 'WADMKK': 'inline label - visible with data', 'WIADKK': 'inline label - visible with data', 'WADMPR': 'inline label - visible with data', 'WIADPR': 'inline label - visible with data', 'TIPADM': 'inline label - visible with data', 'SHAPE_Leng': 'inline label - visible with data', 'SHAPE_Area': 'inline label - visible with data', 'Denpasar_Kode_Kelurahan': 'inline label - visible with data', 'Denpasar_Kode_Kecamatan': 'inline label - visible with data', 'Denpasar_Jumlah_PUS': 'inline label - visible with data', 'Denpasar_UnmetNeed_Spacing': 'inline label - visible with data', 'Denpasar_UnmetNeed_Limiting': 'inline label - visible with data', 'Denpasar_Jumlah_UnmetNeed': 'inline label - visible with data', 'Denpasar_Persentase_UnmetNeed': 'inline label - visible with data', });
lyr_KecBadung_11.set('fieldLabels', {'KDPPUM': 'inline label - visible with data', 'NAMOBJ': 'inline label - visible with data', 'REMARK': 'inline label - visible with data', 'KDPBPS': 'inline label - visible with data', 'FCODE': 'inline label - visible with data', 'LUASWH': 'inline label - visible with data', 'UUPP': 'inline label - visible with data', 'SRS_ID': 'inline label - visible with data', 'LCODE': 'inline label - visible with data', 'METADATA': 'inline label - visible with data', 'KDEBPS': 'inline label - visible with data', 'KDEPUM': 'inline label - visible with data', 'KDCBPS': 'inline label - visible with data', 'KDCPUM': 'inline label - visible with data', 'KDBBPS': 'inline label - visible with data', 'KDBPUM': 'inline label - visible with data', 'WADMKD': 'inline label - visible with data', 'WIADKD': 'inline label - visible with data', 'WADMKC': 'inline label - visible with data', 'WIADKC': 'inline label - visible with data', 'WADMKK': 'inline label - visible with data', 'WIADKK': 'inline label - visible with data', 'WADMPR': 'inline label - visible with data', 'WIADPR': 'inline label - visible with data', 'TIPADM': 'inline label - visible with data', 'SHAPE_Leng': 'inline label - visible with data', 'SHAPE_Area': 'inline label - visible with data', 'KecBadung_Kode_Kecamatan': 'inline label - visible with data', 'KecBadung_Kode_Kabupaten': 'inline label - visible with data', 'KecBadung_Jumlah_PUS': 'inline label - visible with data', 'KecBadung_UnmetNeed_Spacing': 'inline label - visible with data', 'KecBadung_UnmetNeed_Limiting': 'inline label - visible with data', 'KecBadung_Jumlah_UnmetNeed': 'inline label - visible with data', 'KecBadung_Persentase_UnmetNeed': 'inline label - visible with data', });
lyr_KecBangli_12.set('fieldLabels', {'KDPPUM': 'inline label - visible with data', 'NAMOBJ': 'inline label - visible with data', 'REMARK': 'inline label - visible with data', 'KDPBPS': 'inline label - visible with data', 'FCODE': 'inline label - visible with data', 'LUASWH': 'inline label - visible with data', 'UUPP': 'inline label - visible with data', 'SRS_ID': 'inline label - visible with data', 'LCODE': 'inline label - visible with data', 'METADATA': 'inline label - visible with data', 'KDEBPS': 'inline label - visible with data', 'KDEPUM': 'inline label - visible with data', 'KDCBPS': 'inline label - visible with data', 'KDCPUM': 'inline label - visible with data', 'KDBBPS': 'inline label - visible with data', 'KDBPUM': 'inline label - visible with data', 'WADMKD': 'inline label - visible with data', 'WIADKD': 'inline label - visible with data', 'WADMKC': 'inline label - visible with data', 'WIADKC': 'inline label - visible with data', 'WADMKK': 'inline label - visible with data', 'WIADKK': 'inline label - visible with data', 'WADMPR': 'inline label - visible with data', 'WIADPR': 'inline label - visible with data', 'TIPADM': 'inline label - visible with data', 'SHAPE_Leng': 'inline label - visible with data', 'SHAPE_Area': 'inline label - visible with data', 'KecBangli_Kode_Kecamatan': 'inline label - visible with data', 'KecBangli_Kode_Kabupaten': 'inline label - visible with data', 'KecBangli_Jumlah_PUS': 'inline label - visible with data', 'KecBangli_UnmetNeed_Spacing': 'inline label - visible with data', 'KecBangli_UnmetNeed_Limiting': 'inline label - visible with data', 'KecBangli_Jumlah_UnmetNeed': 'inline label - visible with data', 'KecBangli_Persentase_UnmetNeed': 'inline label - visible with data', });
lyr_KecBuleleng_13.set('fieldLabels', {'KDPPUM': 'inline label - visible with data', 'NAMOBJ': 'inline label - visible with data', 'REMARK': 'inline label - visible with data', 'KDPBPS': 'inline label - visible with data', 'FCODE': 'inline label - visible with data', 'LUASWH': 'inline label - visible with data', 'UUPP': 'inline label - visible with data', 'SRS_ID': 'inline label - visible with data', 'LCODE': 'inline label - visible with data', 'METADATA': 'inline label - visible with data', 'KDEBPS': 'inline label - visible with data', 'KDEPUM': 'inline label - visible with data', 'KDCBPS': 'inline label - visible with data', 'KDCPUM': 'inline label - visible with data', 'KDBBPS': 'inline label - visible with data', 'KDBPUM': 'inline label - visible with data', 'WADMKD': 'inline label - visible with data', 'WIADKD': 'inline label - visible with data', 'WADMKC': 'inline label - visible with data', 'WIADKC': 'inline label - visible with data', 'WADMKK': 'inline label - visible with data', 'WIADKK': 'inline label - visible with data', 'WADMPR': 'inline label - visible with data', 'WIADPR': 'inline label - visible with data', 'TIPADM': 'inline label - visible with data', 'SHAPE_Leng': 'inline label - visible with data', 'SHAPE_Area': 'inline label - visible with data', 'KecBuleleng_Kode_Kecamatan': 'inline label - visible with data', 'KecBuleleng_Kode_Kabupaten': 'inline label - visible with data', 'KecBuleleng_Jumlah_PUS': 'inline label - visible with data', 'KecBuleleng_UnmetNeed_Spacing': 'inline label - visible with data', 'KecBuleleng_UnmetNeed_Limiting': 'inline label - visible with data', 'KecBuleleng_Jumlah_UnmetNeed': 'inline label - visible with data', 'KecBuleleng_Persentase_UnmetNeed': 'inline label - visible with data', });
lyr_KecGianyar_14.set('fieldLabels', {'KDPPUM': 'inline label - visible with data', 'NAMOBJ': 'inline label - visible with data', 'REMARK': 'inline label - visible with data', 'KDPBPS': 'inline label - visible with data', 'FCODE': 'inline label - visible with data', 'LUASWH': 'inline label - visible with data', 'UUPP': 'inline label - visible with data', 'SRS_ID': 'inline label - visible with data', 'LCODE': 'inline label - visible with data', 'METADATA': 'inline label - visible with data', 'KDEBPS': 'inline label - visible with data', 'KDEPUM': 'inline label - visible with data', 'KDCBPS': 'inline label - visible with data', 'KDCPUM': 'inline label - visible with data', 'KDBBPS': 'inline label - visible with data', 'KDBPUM': 'inline label - visible with data', 'WADMKD': 'inline label - visible with data', 'WIADKD': 'inline label - visible with data', 'WADMKC': 'inline label - visible with data', 'WIADKC': 'inline label - visible with data', 'WADMKK': 'inline label - visible with data', 'WIADKK': 'inline label - visible with data', 'WADMPR': 'inline label - visible with data', 'WIADPR': 'inline label - visible with data', 'TIPADM': 'inline label - visible with data', 'SHAPE_Leng': 'inline label - visible with data', 'SHAPE_Area': 'inline label - visible with data', 'KecGianyar_Kode_Kecamatan': 'inline label - visible with data', 'KecGianyar_Kode_Kabupaten': 'inline label - visible with data', 'KecGianyar_Jumlah_PUS': 'inline label - visible with data', 'KecGianyar_UnmetNeed_Spacing': 'inline label - visible with data', 'KecGianyar_UnmetNeed_Limiting': 'inline label - visible with data', 'KecGianyar_Jumlah_UnmetNeed': 'inline label - visible with data', 'KecGianyar_Persentase_UnmetNeed': 'inline label - visible with data', });
lyr_KecJembrana_15.set('fieldLabels', {'KDPPUM': 'inline label - visible with data', 'NAMOBJ': 'inline label - visible with data', 'REMARK': 'inline label - visible with data', 'KDPBPS': 'inline label - visible with data', 'FCODE': 'inline label - visible with data', 'LUASWH': 'inline label - visible with data', 'UUPP': 'inline label - visible with data', 'SRS_ID': 'inline label - visible with data', 'LCODE': 'inline label - visible with data', 'METADATA': 'inline label - visible with data', 'KDEBPS': 'inline label - visible with data', 'KDEPUM': 'inline label - visible with data', 'KDCBPS': 'inline label - visible with data', 'KDCPUM': 'inline label - visible with data', 'KDBBPS': 'inline label - visible with data', 'KDBPUM': 'inline label - visible with data', 'WADMKD': 'inline label - visible with data', 'WIADKD': 'inline label - visible with data', 'WADMKC': 'inline label - visible with data', 'WIADKC': 'inline label - visible with data', 'WADMKK': 'inline label - visible with data', 'WIADKK': 'inline label - visible with data', 'WADMPR': 'inline label - visible with data', 'WIADPR': 'inline label - visible with data', 'TIPADM': 'inline label - visible with data', 'SHAPE_Leng': 'inline label - visible with data', 'SHAPE_Area': 'inline label - visible with data', 'KecJembrana_Kode_Kecamatan': 'inline label - visible with data', 'KecJembrana_Kode_Kabupaten': 'inline label - visible with data', 'KecJembrana_Jumlah_PUS': 'inline label - visible with data', 'KecJembrana_UnmetNeed_Spacing': 'inline label - visible with data', 'KecJembrana_UnmetNeed_Limiting': 'inline label - visible with data', 'KecJembrana_Jumlah_UnmetNeed': 'inline label - visible with data', 'KecJembrana_Persentase_UnmetNeed': 'inline label - visible with data', });
lyr_KecKarangasem_16.set('fieldLabels', {'KDPPUM': 'inline label - visible with data', 'NAMOBJ': 'inline label - visible with data', 'REMARK': 'inline label - visible with data', 'KDPBPS': 'inline label - visible with data', 'FCODE': 'inline label - visible with data', 'LUASWH': 'inline label - visible with data', 'UUPP': 'inline label - visible with data', 'SRS_ID': 'inline label - visible with data', 'LCODE': 'inline label - visible with data', 'METADATA': 'inline label - visible with data', 'KDEBPS': 'inline label - visible with data', 'KDEPUM': 'inline label - visible with data', 'KDCBPS': 'inline label - visible with data', 'KDCPUM': 'inline label - visible with data', 'KDBBPS': 'inline label - visible with data', 'KDBPUM': 'inline label - visible with data', 'WADMKD': 'inline label - visible with data', 'WIADKD': 'inline label - visible with data', 'WADMKC': 'inline label - visible with data', 'WIADKC': 'inline label - visible with data', 'WADMKK': 'inline label - visible with data', 'WIADKK': 'inline label - visible with data', 'WADMPR': 'inline label - visible with data', 'WIADPR': 'inline label - visible with data', 'TIPADM': 'inline label - visible with data', 'SHAPE_Leng': 'inline label - visible with data', 'SHAPE_Area': 'inline label - visible with data', 'KecKarangasem_Kode_Kecamatan': 'inline label - visible with data', 'KecKarangasem_Kode_Kabupaten': 'inline label - visible with data', 'KecKarangasem_Jumlah_PUS': 'inline label - visible with data', 'KecKarangasem_UnmetNeed_Spacing': 'inline label - visible with data', 'KecKarangasem_UnmetNeed_Limiting': 'inline label - visible with data', 'KecKarangasem_Jumlah_UnmetNeed': 'inline label - visible with data', 'KecKarangasem_Persentase_UnmetNeed': 'inline label - visible with data', });
lyr_KecKlungkung_17.set('fieldLabels', {'KDPPUM': 'inline label - visible with data', 'NAMOBJ': 'inline label - visible with data', 'REMARK': 'inline label - visible with data', 'KDPBPS': 'inline label - visible with data', 'FCODE': 'inline label - visible with data', 'LUASWH': 'inline label - visible with data', 'UUPP': 'inline label - visible with data', 'SRS_ID': 'inline label - visible with data', 'LCODE': 'inline label - visible with data', 'METADATA': 'inline label - visible with data', 'KDEBPS': 'inline label - visible with data', 'KDEPUM': 'inline label - visible with data', 'KDCBPS': 'inline label - visible with data', 'KDCPUM': 'inline label - visible with data', 'KDBBPS': 'inline label - visible with data', 'KDBPUM': 'inline label - visible with data', 'WADMKD': 'inline label - visible with data', 'WIADKD': 'inline label - visible with data', 'WADMKC': 'inline label - visible with data', 'WIADKC': 'inline label - visible with data', 'WADMKK': 'inline label - visible with data', 'WIADKK': 'inline label - visible with data', 'WADMPR': 'inline label - visible with data', 'WIADPR': 'inline label - visible with data', 'TIPADM': 'inline label - visible with data', 'SHAPE_Leng': 'inline label - visible with data', 'SHAPE_Area': 'inline label - visible with data', 'KecKlungkung_Kode_Kecamatan': 'inline label - visible with data', 'KecKlungkung_Kode_Kabupaten': 'inline label - visible with data', 'KecKlungkung_Jumlah_PUS': 'inline label - visible with data', 'KecKlungkung_UnmetNeed_Spacing': 'inline label - visible with data', 'KecKlungkung_UnmetNeed_Limiting': 'inline label - visible with data', 'KecKlungkung_Jumlah_UnmetNeed': 'inline label - visible with data', 'KecKlungkung_Persentase_UnmetNeed': 'inline label - visible with data', });
lyr_KecTabanan_18.set('fieldLabels', {'KDPPUM': 'inline label - visible with data', 'NAMOBJ': 'inline label - visible with data', 'REMARK': 'inline label - visible with data', 'KDPBPS': 'inline label - visible with data', 'FCODE': 'inline label - visible with data', 'LUASWH': 'inline label - visible with data', 'UUPP': 'inline label - visible with data', 'SRS_ID': 'inline label - visible with data', 'LCODE': 'inline label - visible with data', 'METADATA': 'inline label - visible with data', 'KDEBPS': 'inline label - visible with data', 'KDEPUM': 'inline label - visible with data', 'KDCBPS': 'inline label - visible with data', 'KDCPUM': 'inline label - visible with data', 'KDBBPS': 'inline label - visible with data', 'KDBPUM': 'inline label - visible with data', 'WADMKD': 'inline label - visible with data', 'WIADKD': 'inline label - visible with data', 'WADMKC': 'inline label - visible with data', 'WIADKC': 'inline label - visible with data', 'WADMKK': 'inline label - visible with data', 'WIADKK': 'inline label - visible with data', 'WADMPR': 'inline label - visible with data', 'WIADPR': 'inline label - visible with data', 'TIPADM': 'inline label - visible with data', 'SHAPE_Leng': 'inline label - visible with data', 'SHAPE_Area': 'inline label - visible with data', 'KecTabanan_Kode_Kecamatan': 'inline label - visible with data', 'KecTabanan_Kode_Kabupaten': 'inline label - visible with data', 'KecTabanan_Jumlah_PUS': 'inline label - visible with data', 'KecTabanan_UnmetNeed_Spacing': 'inline label - visible with data', 'KecTabanan_UnmetNeed_Limiting': 'inline label - visible with data', 'KecTabanan_Jumlah_UnmetNeed': 'inline label - visible with data', 'KecTabanan_Persentase_UnmetNeed': 'inline label - visible with data', });
lyr_KecDenpasar_19.set('fieldLabels', {'KDPPUM': 'inline label - visible with data', 'NAMOBJ': 'inline label - visible with data', 'REMARK': 'inline label - visible with data', 'KDPBPS': 'inline label - visible with data', 'FCODE': 'inline label - visible with data', 'LUASWH': 'inline label - visible with data', 'UUPP': 'inline label - visible with data', 'SRS_ID': 'inline label - visible with data', 'LCODE': 'inline label - visible with data', 'METADATA': 'inline label - visible with data', 'KDEBPS': 'inline label - visible with data', 'KDEPUM': 'inline label - visible with data', 'KDCBPS': 'inline label - visible with data', 'KDCPUM': 'inline label - visible with data', 'KDBBPS': 'inline label - visible with data', 'KDBPUM': 'inline label - visible with data', 'WADMKD': 'inline label - visible with data', 'WIADKD': 'inline label - visible with data', 'WADMKC': 'inline label - visible with data', 'WIADKC': 'inline label - visible with data', 'WADMKK': 'inline label - visible with data', 'WIADKK': 'inline label - visible with data', 'WADMPR': 'inline label - visible with data', 'WIADPR': 'inline label - visible with data', 'TIPADM': 'inline label - visible with data', 'SHAPE_Leng': 'inline label - visible with data', 'SHAPE_Area': 'inline label - visible with data', 'KecDenpasar_Kode_Kecamatan': 'inline label - visible with data', 'KecDenpasar_Kode_Kabupaten': 'inline label - visible with data', 'KecDenpasar_Jumlah_PUS': 'inline label - visible with data', 'KecDenpasar_UnmetNeed_Spacing': 'inline label - visible with data', 'KecDenpasar_UnmetNeed_Limiting': 'inline label - visible with data', 'KecDenpasar_Jumlah_UnmetNeed': 'inline label - visible with data', 'KecDenpasar_Persentase_UnmetNeed': 'inline label - visible with data', });
lyr_BALI_20.set('fieldLabels', {'PROVINSI': 'inline label - visible with data', 'KABKOT': 'inline label - visible with data', 'KECAMATAN': 'inline label - visible with data', 'KODE': 'inline label - visible with data', 'DESA': 'inline label - visible with data', 'Kabupaten_Kode_Kabupaten': 'inline label - visible with data', 'Kabupaten_Jumlah_PUS': 'inline label - visible with data', 'Kabupaten_UnmetNeed_Spacing': 'inline label - visible with data', 'Kabupaten_UnmetNeed_Limiting': 'inline label - visible with data', 'Kabupaten_Jumlah_UnmetNeed': 'inline label - visible with data', 'Kabupaten_Persentase_UnmetNeed': 'inline label - visible with data', });
lyr_BALI_20.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});